const NAME_KEY = 'mojito-inn-operator';
const ORDERS_KEY = 'mojito-inn-simple-orders-v1';
const THEME_KEY = 'mojito-inn-theme';
const CITIZEN_SALES_KEY = 'mojito-inn-citizen-sales-v1';
const GAME_SORT_KEY = 'mojito-inn-game-sort';
const SOUND_KEY = 'mojito-inn-remote-sound';
const ACCESS_KEY = 'mojito-inn-access-granted';
const number = new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 2 });
const config = window.MOJITO_CONFIG || {};
const configured = /^https:\/\/.+\.supabase\.co$/.test(config.supabaseUrl || '') && !String(config.supabaseKey).startsWith('COLLE_');
const db = configured && window.supabase ? window.supabase.createClient(config.supabaseUrl, config.supabaseKey) : null;
let operatorName = localStorage.getItem(NAME_KEY) || '';
let state = { balance: 0, peak: 0, history: [], updated: Date.now() };
let cart = [];
let appMode = 'tab';
let expenses = [];
let gifts=[];
let services={current:null,history:[]};
let salesEvents=[];
let weeklyStats=[];
let selectedWeek='current';
let selectedStatsDay=null;
let weeklyPieSellers=[];
let editingGiftId=null;
let raffle={price:100,max:10,winner:null,entries:[]};
let citizenSales=Number(localStorage.getItem(CITIZEN_SALES_KEY))||0;
let teamStats=[];
let game={title:'Nouvelle partie',type:'Blind Test',scores:[],logs:[],winners:[],winnersError:false};
let gameSort=localStorage.getItem(GAME_SORT_KEY)||'order';
let soundEnabled=localStorage.getItem(SOUND_KEY)==='on';
let remoteAlertCount=0;
let savedOrders = loadOrders();
let happyHour = false;

function loadOrders(){try{return JSON.parse(localStorage.getItem(ORDERS_KEY))||[]}catch{return[]}}
function saveOrders(){localStorage.setItem(ORDERS_KEY,JSON.stringify(savedOrders));renderOrderLogs()}
function renderCitizenSales(){document.querySelector('#citizen-sales-count').textContent=format(citizenSales)}
function applyTheme(theme){
  if(theme!=='contrast')theme='sand';document.body.classList.toggle('theme-contrast',theme==='contrast');document.body.dataset.theme=theme;
  const button=document.querySelector('#theme-toggle');button.querySelector('span').innerHTML=theme==='contrast'?'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M19.1 4.9l-1.4 1.4M6.3 17.7l-1.4 1.4"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.2A8.5 8.5 0 1 1 8.8 4a7 7 0 0 0 11.2 11.2Z"/></svg>';button.setAttribute('aria-label',theme==='contrast'?'Activer le mode clair':'Activer le mode sombre');
}

const format = value => number.format(Number(value));
const parseAmount = value => Number(value.trim().replace(/\s/g, '').replace(',', '.'));
const isAdminName = name => ['kai','summer'].includes(String(name||'').trim().toLowerCase());
const escapeHTML = value => String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function toast(message) { const el=document.querySelector('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2500); }
let alertAudioContext;
function updateSoundButton(){const button=document.querySelector('#sound-toggle');button.querySelector('span').innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/>${soundEnabled?'':'<path class="sound-slash" d="M4 4l16 16"/>'}</svg>`;button.title=soundEnabled?'Couper les alertes sonores':'Activer les alertes sonores';button.setAttribute('aria-label',button.title);button.classList.toggle('active',soundEnabled)}
function playRemoteSound(){if(!soundEnabled)return;try{alertAudioContext=alertAudioContext||new(window.AudioContext||window.webkitAudioContext)();const now=alertAudioContext.currentTime,gain=alertAudioContext.createGain();gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.45);gain.connect(alertAudioContext.destination);[659.25,783.99].forEach((frequency,index)=>{const oscillator=alertAudioContext.createOscillator();oscillator.type='sine';oscillator.frequency.value=frequency;oscillator.connect(gain);oscillator.start(now+index*.07);oscillator.stop(now+.48)})}catch{}}
function showTeamAlert(message,kind='payment',mode='tab'){const alert=document.querySelector('#remote-alert');alert.dataset.mode=mode;alert.querySelector('b').textContent=message;alert.querySelector('small').textContent=mode==='tab'?'Voir l’ardoise':mode==='expenses'?'Voir les dépenses':mode==='gifts'?'Voir les cadeaux':mode==='games'?'Voir les jeux':'Voir le service';alert.classList.add('show',kind);alert.classList.remove(kind==='addition'?'payment':'addition');clearTimeout(showTeamAlert.timer);showTeamAlert.timer=setTimeout(()=>alert.classList.remove('show'),5000);playRemoteSound()}
function showRemoteAlert(row){if(!row||String(row.operator_name||'').trim().toLowerCase()===operatorName.trim().toLowerCase())return;const alert=document.querySelector('#remote-alert'),amount=Number(row.amount||0),quantity=Number(row.quantity||1);remoteAlertCount=Date.now()-Number(alert.dataset.last||0)<1800?remoteAlertCount+1:1;alert.dataset.last=Date.now();const message=remoteAlertCount>1?`${remoteAlertCount} nouvelles opérations sur l’ardoise`:row.operation==='add'?`${row.operator_name} a ajouté ${format(amount)} à l’ardoise`:`${row.operator_name} a déduit ${quantity>1?quantity+' × ':''}${row.item_name||format(amount)}`;showTeamAlert(message,row.operation==='add'?'addition':'payment','tab')}
function syncStatus(text, kind='') { const el=document.querySelector('#sync-status'); el.className=`sync-status ${kind}`; el.querySelector('span').textContent=text; }
function requireName() { if (operatorName) return true; openName(); return false; }

function render() {
  document.querySelector('#operator-name').textContent = operatorName || 'Choisir mon nom';
  document.querySelector('#admin-badge').hidden=!isAdminName(operatorName);
  document.querySelector('#open-access-settings').hidden=!isAdminName(operatorName);
  document.querySelector('.admin-service-tab').hidden=false;
  document.querySelector('#balance').textContent = format(state.balance);
  document.querySelector('#updated').textContent = state.history.length ? `Mis à jour à ${new Date(state.updated).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}` : 'Prêt à démarrer';
  document.querySelector('#progress').style.width = `${state.peak ? Math.min(100, state.balance/state.peak*100) : 0}%`;
  document.querySelector('#balance-note').textContent = state.balance ? `${format(Math.max(0,state.peak-state.balance))} déjà déduits de cette ardoise.` : 'L’ardoise est vide — tout est réglé !';
  document.querySelector('#count').textContent = `${state.history.length} opération${state.history.length>1?'s':''}`;
  document.querySelector('#history').innerHTML = state.history.length ? state.history.slice(0,50).map(item=>`
    <li><span class="history-icon ${item.type}">${item.type==='add'?'+':'−'}</span>
    <span class="history-info"><b>${item.type==='add'?'Ajout à l’ardoise':`${item.quantity>1?item.quantity+' × ':''}${item.name}`}</b><small>${item.operator} · ${new Date(item.date).toLocaleString('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small></span>
    <span class="history-amount ${item.type}">${item.type==='add'?'+':'−'} ${format(item.amount)}</span>${item.type==='payment'&&(isAdminName(operatorName)||item.operator.toLowerCase()===operatorName.toLowerCase())?`<button class="log-delete" data-log-delete="${item.id}" type="button" title="Annuler cette ligne">×</button>`:''}</li>`).join('') : '<li class="empty">Aucune opération pour le moment 🌺</li>';
}

function renderCart() {
  const total=cart.reduce((sum,item)=>sum+item.amount,0);
  document.querySelector('#cart-total').textContent=format(total);
  document.querySelector('#cart-count').textContent=cart.length?`${cart.length} article${cart.length>1?'s':''}`:'Aucun article';
  const counts=new Map(); cart.forEach(item=>{const key=`${item.name}|${item.amount}`; const old=counts.get(key)||{...item,qty:0}; old.qty++; counts.set(key,old)});
  document.querySelector('#cart-lines').innerHTML=[...counts.values()].map(item=>`<li><span>${item.qty} × ${item.name}</span><span>${format(item.qty*item.amount)}</span></li>`).join('');
  document.querySelector('#validate-cart').disabled=!cart.length;
  document.querySelector('#validate-cart').textContent=appMode==='tab'?'Valider et déduire':'Commande encaissée';
  document.querySelector('#undo-item').disabled=!cart.length; document.querySelector('#clear-cart').disabled=!cart.length;
}

function renderExpenses(){
  const total=expenses.reduce((sum,item)=>sum+item.amount,0);
  document.querySelector('#expense-total').textContent=format(total);
  document.querySelector('#expense-count').textContent=`${expenses.length} dépense${expenses.length>1?'s':''}`;
  document.querySelector('#expense-history').innerHTML=expenses.length?expenses.map(item=>`<li><span class="history-icon add">−</span><span class="history-info"><b>${escapeHTML(item.label)}</b><small>${escapeHTML(item.category)} · ${escapeHTML(item.operator)} · ${new Date(item.date).toLocaleString('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small></span><span class="history-amount">− ${format(item.amount)}</span>${isAdminName(operatorName)||item.operator.toLowerCase()===operatorName.toLowerCase()?`<button class="log-delete" data-expense-delete="${item.id}" type="button" title="Annuler cette dépense">×</button>`:''}</li>`).join(''):'<li class="empty">Aucune dépense enregistrée 🌺</li>';
}

function renderGifts(){
  const active=gifts.filter(x=>x.status==='active'),history=gifts.filter(x=>x.status==='completed'),money=gifts.filter(x=>x.type==='money').reduce((sum,x)=>sum+x.amount,0),drinks=active.filter(x=>x.type==='drink').reduce((sum,x)=>sum+x.remaining,0),people=new Set(active.map(x=>x.name.toLowerCase())).size,admin=isAdminName(operatorName);
  const card=(item,archived=false)=>`<article class="gift-item ${item.type} ${archived?'archived':''}"><div class="gift-icon">${item.type==='drink'?'🍹':'💵'}</div><div class="gift-info"><b>${escapeHTML(item.name)}</b>${item.phone?`<a href="tel:${escapeHTML(item.phone)}">📞 ${escapeHTML(item.phone)}</a>`:''}<small>${item.type==='drink'?`${item.remaining} restante${item.remaining>1?'s':''} sur ${item.quantity}`:`${format(item.amount)} offerts`}${item.note?' · '+escapeHTML(item.note):''}</small><em>${archived?'Terminé':'Ajouté'} · par ${escapeHTML(item.operator)} · ${new Date(archived&&item.completed?item.completed:item.date).toLocaleDateString('fr-FR')}</em></div><div class="gift-actions">${!archived&&item.type==='drink'?`<button class="gift-use" data-gift-use="${item.id}" type="button" ${item.remaining<1?'disabled':''}>−1 conso</button>${item.remaining<item.quantity?`<button class="gift-restore" data-gift-restore="${item.id}" type="button">＋1</button>`:''}`:''}${archived&&item.type==='drink'?`<button class="gift-restore" data-gift-restore="${item.id}" type="button">Réactiver +1</button>`:''}${!archived?`<button class="gift-finish" data-gift-finish="${item.id}" type="button">Terminer</button><button class="gift-edit" data-gift-edit="${item.id}" type="button">Modifier</button>`:''}${admin?`<button class="gift-delete" data-gift-delete="${item.id}" type="button" title="Supprimer ce cadeau">×</button>`:''}</div></article>`;
  document.querySelector('#gift-money-total').textContent=format(money);document.querySelector('#gift-drinks-left').textContent=drinks;document.querySelector('#gift-people-count').textContent=people;document.querySelector('#gift-count').textContent=`${active.length} en cours`;document.querySelector('#gift-history-count').textContent=`${history.length} terminé${history.length>1?'s':''}`;document.querySelector('#reset-gifts').hidden=!admin;
  document.querySelector('#gift-list').innerHTML=active.length?active.map(x=>card(x)).join(''):'<div class="team-empty">Aucun cadeau en cours</div>';document.querySelector('#gift-history').innerHTML=history.length?history.map(x=>card(x,true)).join(''):'<div class="team-empty">Aucun cadeau terminé</div>';
}

function formatDuration(milliseconds){if(milliseconds<=0)return'0 min';const minutes=Math.floor(milliseconds/60000),hours=Math.floor(minutes/60),rest=minutes%60;return hours?`${hours} h ${String(rest).padStart(2,'0')}`:`${minutes} min`}
function getServiceWeek(now=new Date()){const start=new Date(now);const daysSinceSunday=now.getDay();start.setDate(now.getDate()-daysSinceSunday);start.setHours(20,0,0,0);if(now<start)start.setDate(start.getDate()-7);const end=new Date(start);end.setDate(end.getDate()+7);return{start,end}}
function getAutomaticServiceName(date=new Date()){const value=date.toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long'});return value.charAt(0).toUpperCase()+value.slice(1)}
function localDateKey(date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}:00`}
function aggregateSales(events,keyMaker){const groups=new Map();events.forEach(event=>{const key=keyMaker(event),value=groups.get(key)||{revenue:0,items:0,orders:0};value.revenue+=event.revenue;value.items+=event.items;value.orders+=event.orders;groups.set(key,value)});return groups}
function renderBarChart(selector,entries,emptyText='Aucune vente enregistrée'){const container=document.querySelector(selector);if(!entries.length){container.innerHTML=`<span class="chart-empty">${emptyText}</span>`;return}const max=Math.max(...entries.map(entry=>entry.value),1);container.innerHTML=entries.map(entry=>`<span class="chart-column"${entry.key!==undefined?` data-chart-key="${entry.key}" tabindex="0"`:''} title="${escapeHTML(entry.title||entry.label)}"><b>${entry.value?format(entry.value):'—'}</b><i class="chart-bar" style="height:${Math.max(3,entry.value/max*55)}px"></i><small>${escapeHTML(entry.label)}</small></span>`).join('')}
function renderLineChart(selector,entries){const container=document.querySelector(selector);container.classList.add('service-line-chart');if(!entries.length){container.innerHTML='<span class="chart-empty">Les ventes horaires apparaîtront ici</span>';return}const width=320,height=92,padX=22,padTop=12,padBottom=18,max=Math.max(...entries.map(entry=>entry.value),1),step=entries.length>1?(width-padX*2)/(entries.length-1):0,points=entries.map((entry,index)=>({x:entries.length>1?padX+index*step:width/2,y:padTop+(max-entry.value)/max*(height-padTop-padBottom),...entry})),path=points.map((point,index)=>`${index?'L':'M'}${point.x},${point.y}`).join(' '),area=`${path} L${points.at(-1).x},${height-padBottom} L${points[0].x},${height-padBottom} Z`;container.innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Encaissement heure par heure"><defs><linearGradient id="serviceLineGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ed7a52" stop-opacity=".34"/><stop offset="1" stop-color="#ed7a52" stop-opacity=".03"/></linearGradient></defs><line class="line-grid" x1="${padX}" y1="${height-padBottom}" x2="${width-padX}" y2="${height-padBottom}"/><path class="line-area" d="${area}"/><path class="line-path" d="${path}"/>${points.map(point=>`<circle cx="${point.x}" cy="${point.y}" r="4"><title>${escapeHTML(point.label)} · ${format(point.value)}</title></circle><text x="${point.x}" y="${height-4}" text-anchor="middle">${escapeHTML(point.label)}</text>`).join('')}</svg>`}
function renderSellerPie(groups){const colors=['#ed7658','#18a39b','#f1b84a','#6b78d1','#9a62bd','#48a968','#d65c92','#598ca8'],entries=[...groups.entries()].map(([name,value])=>({name,value:value.revenue})).filter(item=>item.value>0).sort((a,b)=>b.value-a.value),total=entries.reduce((sum,item)=>sum+item.value,0),section=document.querySelector('.seller-pie-section');weeklyPieSellers=entries;section.classList.toggle('empty',!entries.length);if(!entries.length){document.querySelector('#seller-pie').style.background='#dce9e4';document.querySelector('#seller-pie-value').textContent=format(0);document.querySelector('#seller-pie-name').textContent='Aucune vente';document.querySelector('#seller-pie-legend').innerHTML='';return}let cursor=0;const segments=entries.map((entry,index)=>{const start=cursor;cursor+=entry.value/total*360;return`${colors[index%colors.length]} ${start}deg ${cursor}deg`});document.querySelector('#seller-pie').style.background=`conic-gradient(${segments.join(',')})`;document.querySelector('#seller-pie-value').textContent=format(total);document.querySelector('#seller-pie-name').textContent='Total';document.querySelector('#seller-pie-legend').innerHTML=entries.map((entry,index)=>`<button type="button" data-pie-index="${index}"><i style="background:${colors[index%colors.length]}"></i><span>${escapeHTML(entry.name)}</span><b>${Math.round(entry.value/total*100)} %</b></button>`).join('')}
function renderServices(){
  const current=services.current,admin=isAdminName(operatorName),revenue=teamStats.reduce((sum,x)=>sum+x.revenue,0),items=teamStats.reduce((sum,x)=>sum+x.items,0),expenseTotal=expenses.reduce((sum,x)=>sum+x.amount,0);
  const personal=teamStats.find(person=>person.name.toLowerCase()===operatorName.toLowerCase())||{revenue:0,items:0,orders:0};
  document.querySelector('#service-status').textContent=current?`${current.isEvent?'🎉 ':''}${current.name}`:'Aucun service ouvert';
  document.querySelector('#service-meta').textContent=current?`Ouvert par ${current.openedBy} · ${new Date(current.openedAt).toLocaleString('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}`:'Ouvre un service pour commencer le suivi.';
  document.querySelector('#service-status-icon').textContent=current?'🟢':'🌙';
  document.querySelector('#open-service-form').hidden=Boolean(current);
  document.querySelector('#automatic-service-name').textContent=getAutomaticServiceName();
  document.querySelector('#close-service').hidden=!current;
  document.querySelector('#nonadmin-service-summary').hidden=false;
  document.querySelector('.service-report-stats').hidden=!admin;
  document.querySelector('.service-team-card').hidden=!admin;
  document.querySelector('.service-history-card').hidden=!admin;
  document.querySelector('.service-time-card').hidden=!admin;
  document.querySelector('.service-week-card').hidden=!admin;
  document.querySelector('.service-adjust-card').hidden=!admin;
  document.querySelector('#service-export-actions').hidden=!admin;
  document.querySelector('#my-service-revenue').textContent=format(personal.revenue);
  document.querySelector('#my-service-items').textContent=personal.items;
  document.querySelector('#my-service-orders').textContent=personal.orders;
  document.querySelector('#service-revenue').textContent=format(revenue);
  document.querySelector('#service-items').textContent=items;
  document.querySelector('#service-expenses').textContent=format(expenseTotal);
  document.querySelector('#service-net').textContent=format(revenue-expenseTotal);
  const now=Date.now(),openedAt=current?new Date(current.openedAt).getTime():now,currentEvents=current?salesEvents.filter(event=>event.serviceId===current.id):[];
  const duration=current?Math.max(0,now-openedAt):0,hours=Math.max(duration/3600000,1/60),hourGroups=aggregateSales(currentEvents,event=>new Date(event.date).getHours());
  const hourEntries=[...hourGroups.entries()].sort((a,b)=>a[0]-b[0]).map(([hour,value])=>({label:`${String(hour).padStart(2,'0')}h`,value:value.revenue,title:`${value.orders} commande(s) · ${value.items} article(s)`}));
  const peak=hourEntries.reduce((best,item)=>!best||item.value>best.value?item:best,null);
  document.querySelector('#service-live-label').textContent=current?`Mis à jour en direct · ${current.name}`:'Ouvre un service pour démarrer';
  document.querySelector('#service-duration').textContent=current?formatDuration(duration):'—';
  document.querySelector('#service-hourly-average').textContent=current?format(revenue/hours):format(0);
  document.querySelector('#service-peak-hour').textContent=peak?`${peak.label} · ${format(peak.value)}`:'—';
  renderLineChart('#service-hourly-chart',hourEntries);
  const serviceWeek=getServiceWeek(new Date(now)),currentWeekKey=localDateKey(serviceWeek.start),availableWeeks=[...new Set(weeklyStats.map(row=>row.weekStart))].sort().reverse(),selector=document.querySelector('#week-selector');
  if(selectedWeek!=='current'&&!availableWeeks.includes(selectedWeek))selectedWeek='current';
  selector.innerHTML=`<option value="current">Semaine actuelle</option>${availableWeeks.filter(key=>key!==currentWeekKey).map(key=>{const date=new Date(key);return`<option value="${key}">Semaine du ${date.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'2-digit'})}</option>`}).join('')}`;selector.value=selectedWeek;
  const chosenKey=selectedWeek==='current'?currentWeekKey:selectedWeek,chosenStart=new Date(chosenKey),chosenRows=weeklyStats.filter(row=>row.weekStart===chosenKey),dayGroups=aggregateSales(chosenRows,row=>row.day);
  const dayEntries=Array.from({length:7},(_,offset)=>{const date=new Date(chosenStart);date.setDate(date.getDate()+offset);const value=dayGroups.get(date.getDay())||{revenue:0,items:0,orders:0};return{key:offset,label:date.toLocaleDateString('fr-FR',{weekday:'short'}).replace('.',''),value:value.revenue,title:`Cliquer pour le détail · ${value.orders} commande(s) · ${value.items} article(s)`,stats:value}}),weekRevenue=chosenRows.reduce((sum,row)=>sum+row.revenue,0),weekItems=chosenRows.reduce((sum,row)=>sum+row.items,0),weekOrders=chosenRows.reduce((sum,row)=>sum+row.orders,0);
  document.querySelector('#week-title').textContent=selectedWeek==='current'?'Semaine en cours':'Semaine archivée';
  document.querySelector('#week-stats-label').textContent=`Du ${chosenStart.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'})} à 20 h au dimanche suivant`;
  document.querySelector('#week-revenue').textContent=format(weekRevenue);document.querySelector('#week-items').textContent=weekItems;document.querySelector('#week-orders').textContent=weekOrders;
  const sellerGroups=aggregateSales(chosenRows,row=>row.name||'Inconnu');renderSellerPie(sellerGroups);document.querySelector('#week-seller-stats').innerHTML=[...sellerGroups.entries()].sort((a,b)=>b[1].revenue-a[1].revenue).map(([name,value])=>`<div class="week-seller"><b>${escapeHTML(name)}</b><div><span><small>Encaissé</small><strong>${format(value.revenue)}</strong></span><span><small>Articles</small><strong>${value.items}</strong></span><span><small>Commandes</small><strong>${value.orders}</strong></span></div></div>`).join('')||'<div class="team-empty">Aucune vente sur cette semaine</div>';
  const previousStart=new Date(chosenStart);previousStart.setDate(previousStart.getDate()-7);const previousRows=weeklyStats.filter(row=>row.weekStart===localDateKey(previousStart)),previousRevenue=previousRows.reduce((sum,row)=>sum+row.revenue,0),comparison=document.querySelector('#week-comparison');
  comparison.className='week-comparison';if(!previousRows.length){comparison.textContent='Aucune semaine précédente enregistrée'}else{const difference=previousRevenue?Math.round((weekRevenue-previousRevenue)/previousRevenue*100):weekRevenue?100:0;comparison.textContent=`${difference>=0?'▲':'▼'} ${Math.abs(difference)} % d’encaissement par rapport à la semaine précédente`;comparison.classList.add(difference>=0?'positive':'negative')}
  renderBarChart('#week-chart',dayEntries);
  document.querySelector('.service-team-stats').innerHTML=teamStats.length?teamStats.map(person=>`<div class="team-member"><b>${escapeHTML(person.name)}</b><div><span><small>Encaissé</small><strong>${format(person.revenue)}</strong></span><span><small>Articles</small><strong>${person.items}</strong></span><span><small>Commandes</small><strong>${person.orders}</strong></span></div></div>`).join(''):'<div class="team-empty">Aucune vente sur ce service</div>';
  const knownSellers=[...new Set(['Kai','Summer',...teamStats.map(person=>person.name),...weeklyStats.map(row=>row.name)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'})),sellerOptions=knownSellers.map(name=>`<option value="${escapeHTML(name)}">${escapeHTML(name)}${isAdminName(name)?' · ADMIN':''}</option>`).join(''),adjustSelect=document.querySelector('#adjust-person'),previousSeller=adjustSelect.value;adjustSelect.innerHTML=`<option value="">Choisir un vendeur</option>${sellerOptions}`;if(knownSellers.includes(previousSeller))adjustSelect.value=previousSeller;
  const adjustments=salesEvents.filter(event=>event.source==='adjustment').slice().reverse().slice(0,20);document.querySelector('#manual-adjustments').innerHTML=adjustments.length?adjustments.map(event=>`<div class="manual-adjustment"><div><b>${escapeHTML(event.name)}</b><small>${escapeHTML(event.note||'Correction manuelle')} · ${new Date(event.date).toLocaleString('fr-FR',{weekday:'short',hour:'2-digit',minute:'2-digit'})}</small></div><strong>${event.revenue>=0?'+':''}${format(event.revenue)}</strong><button type="button" data-adjust-delete="${event.id}">Annuler</button></div>`).join(''):'<div class="team-empty">Aucune correction manuelle cette semaine</div>';
  document.querySelector('#service-history-count').textContent=`${services.history.length} rapport${services.history.length>1?'s':''}`;
  renderBarChart('#service-comparison-chart',services.history.slice(0,10).reverse().map(service=>({label:`${service.isEvent?'🎉 ':''}${service.name}`,value:Number(service.snapshot?.revenue||0),title:`${service.isEvent?'Event · ':''}${service.name} · ${new Date(service.closedAt).toLocaleDateString('fr-FR')}`})),'Les services clôturés seront comparés ici');
  document.querySelector('#service-history').innerHTML=services.history.length?services.history.map(service=>{const report=service.snapshot||{},net=Number(report.revenue||0)-Number(report.expenses_total||0),hourly=Array.isArray(report.hourly)?report.hourly:[];return `<details class="service-report"><summary><div><b>${escapeHTML(service.name)}</b><small>${new Date(service.closedAt).toLocaleDateString('fr-FR')} · ${report.duration_minutes?formatDuration(Number(report.duration_minutes)*60000)+' · ':''}fermé par ${escapeHTML(service.closedBy||'—')}</small></div><strong>${format(net)}</strong></summary><div class="service-report-detail"><span><small>Encaissé</small><b>${format(report.revenue||0)}</b></span><span><small>Articles</small><b>${report.items||0}</b></span><span><small>Commandes</small><b>${report.orders||0}</b></span><span><small>Dépenses</small><b>${format(report.expenses_total||0)}</b></span><span><small>Argent offert</small><b>${format(report.gift_money||0)}</b></span><span><small>Consos offertes</small><b>${report.gift_drinks||0}</b></span>${hourly.length?`<div class="service-report-hourly"><div class="hourly-chart">${(()=>{const max=Math.max(...hourly.map(x=>Number(x.revenue)),1);return hourly.map(x=>`<span class="chart-column"><b>${format(Number(x.revenue))}</b><i class="chart-bar" style="height:${Math.max(3,Number(x.revenue)/max*42)}px"></i><small>${String(x.hour).padStart(2,'0')}h</small></span>`).join('')})()}</div></div>`:''}</div></details>`}).join(''):'<div class="team-empty">Aucun rapport clôturé</div>';
}
function getExportReport(){if(services.current)return{name:services.current.name,report:{revenue:teamStats.reduce((s,x)=>s+x.revenue,0),items:teamStats.reduce((s,x)=>s+x.items,0),orders:teamStats.reduce((s,x)=>s+x.orders,0),expenses_total:expenses.reduce((s,x)=>s+x.amount,0),team:teamStats,expenses}};const last=services.history[0];return last?{name:last.name,report:last.snapshot||{}}:null}
function downloadServiceCSV(){const source=getExportReport();if(!source)return toast('Aucun rapport disponible');const r=source.report,rows=[['Rapport',source.name],['Encaissé',r.revenue||0],['Articles',r.items||0],['Commandes',r.orders||0],['Dépenses',r.expenses_total||0],[],['Employé','Encaissé','Articles','Commandes'],...(r.team||[]).map(x=>[x.name,x.revenue,x.items,x.orders]),[],['Dépense','Catégorie','Montant','Employé'],...(r.expenses||[]).map(x=>[x.label,x.category,x.amount,x.operator])],csv='\ufeff'+rows.map(row=>row.map(value=>`"${String(value??'').replace(/"/g,'""')}"`).join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`rapport-${source.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.csv`;link.click();URL.revokeObjectURL(url)}

function renderRaffle(){const sold=raffle.entries.reduce((s,x)=>s+x.tickets,0);document.querySelector('#raffle-pot').textContent=format(sold*raffle.price);document.querySelector('#raffle-sold').textContent=sold;document.querySelector('#raffle-max-label').textContent=raffle.max;document.querySelector('#ticket-price').value=raffle.price;document.querySelector('#ticket-max').value=raffle.max;document.querySelector('#raffle-count').textContent=`${raffle.entries.length} participant${raffle.entries.length>1?'s':''}`;document.querySelector('#raffle-winner').querySelector('strong').textContent=raffle.winner||'Pas encore tiré';document.querySelector('#raffle-list').innerHTML=raffle.entries.length?raffle.entries.map(x=>`<li><span class="history-icon">🎟</span><span class="history-info"><b>${x.name}</b><small>Ajouté par ${x.operator}</small></span><span class="history-amount">${x.tickets} ticket${x.tickets>1?'s':''}</span></li>`).join(''):'<li class="empty">Aucun participant pour le moment</li>';updateRaffleCost()}
function updateRaffleCost(){const tickets=Number(document.querySelector('#raffle-tickets').value)||0;document.querySelector('#raffle-entry-cost').textContent=format(tickets*raffle.price)}
function renderGame(){
  const byPoints=[...game.scores].sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name,'fr'));
  const shown=[...game.scores].sort(gameSort==='alpha'?(a,b)=>a.name.localeCompare(b.name,'fr',{sensitivity:'base'}):['points','podium'].includes(gameSort)?(a,b)=>b.points-a.points||a.name.localeCompare(b.name,'fr'):(a,b)=>a.id-b.id).slice(0,gameSort==='podium'?3:undefined);
  document.querySelector('#game-sort').value=gameSort;
  const modeLabels={order:'Ordre d’ajout',alpha:'Ordre alphabétique',points:'Classement par points',podium:'Les trois premiers'};
  document.querySelector('#game-list-mode').textContent=`${modeLabels[gameSort]} · mise à jour en direct`;
  document.querySelector('#game-title').value=game.title==='Nouvelle partie'?'':game.title;document.querySelector('#game-type').value=game.type;document.querySelector('#game-heading').textContent=gameSort==='podium'?'Podium':game.title||'Joueurs';document.querySelector('#game-player-count').textContent=game.scores.length;document.querySelector('#game-total-points').textContent=game.scores.reduce((sum,x)=>sum+x.points,0);document.querySelector('#game-leader').textContent=byPoints.length&&byPoints[0].points>0?byPoints.filter(x=>x.points===byPoints[0].points).map(x=>x.name).join(', '):'—';
  document.querySelector('#leaderboard').innerHTML=shown.length?shown.map((player,index)=>`<li><span class="rank">${index+1}</span><span class="leader-info"><b>${escapeHTML(player.name)}</b></span><span class="score-controls"><button data-score-id="${player.id}" data-delta="-1" type="button">−1</button><strong>${player.points}</strong><button data-score-id="${player.id}" data-delta="1" type="button">+1</button><button class="plus-two" data-score-id="${player.id}" data-delta="2" type="button">+2</button><button class="delete-player" data-delete-score="${player.id}" type="button">×</button></span></li>`).join(''):'<li class="empty">Ajoute un nom pour commencer 🎵</li>';
  document.querySelector('#game-log-count').textContent=`${game.logs.length} attribution${game.logs.length>1?'s':''}`;document.querySelector('#game-log').innerHTML=game.logs.length?game.logs.slice(0,50).map(log=>`<li><span class="history-icon ${log.delta<0?'add':''}">${log.delta>0?'+':'−'}</span><span class="history-info"><b>${escapeHTML(log.player)}</b><small>${escapeHTML(log.operator)} · ${new Date(log.date).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small></span><span class="history-amount ${log.delta<0?'add':''}">${log.delta>0?'+':''}${log.delta}</span></li>`).join(''):'<li class="empty">Aucun point attribué</li>'
}

function renderPreviousWinners(){
  document.querySelector('#reset-game-winners').hidden=!isAdminName(operatorName);
  document.querySelector('#previous-winners').innerHTML=game.winnersError?'<div class="team-empty winners-error">Historique non installé dans Supabase</div>':game.winners.length?game.winners.map(game=>{const podium=[game.first,game.second,game.third].filter(x=>x.name),all=game.standings.length?game.standings:podium;return `<details class="previous-winner"><summary><small>Partie · toucher pour ouvrir</small><b>🏆 ${escapeHTML(game.title)}</b><ol class="winner-podium">${podium.map((player,index)=>`<li><em>${['🥇','🥈','🥉'][index]}</em><span>${escapeHTML(player.name)}</span><strong>${player.points} pt</strong></li>`).join('')}</ol></summary><div class="full-game-ranking"><small>Classement complet · ${all.length} joueur${all.length>1?'s':''}</small><ol>${all.map((player,index)=>`<li><em>${index+1}</em><span>${escapeHTML(player.name)}</span><strong>${player.points} pt</strong></li>`).join('')}</ol>${isAdminName(operatorName)?`<button class="delete-archived-game" data-delete-game="${game.id}" type="button">Supprimer cette partie</button>`:''}</div></details>`}).join(''):'<div class="team-empty">Aucune partie terminée avec des points</div>'
}

function renderOrderLogs(){
  const revenue=savedOrders.reduce((sum,order)=>sum+order.total,0),itemCount=savedOrders.reduce((sum,order)=>sum+order.items.length,0);
  const shared=teamStats.find(person=>person.name.toLowerCase()===operatorName.toLowerCase());
  document.querySelector('#order-revenue').textContent=format(shared?shared.revenue:revenue);
  document.querySelector('#order-items').textContent=format(shared?shared.items:itemCount);
  document.querySelector('#order-count').textContent=format(shared?shared.orders:savedOrders.length);
  document.querySelector('#saved-orders-count').textContent=`${savedOrders.length} commande${savedOrders.length>1?'s':''}`;
  const products=new Map();savedOrders.forEach(order=>order.items.forEach(item=>{const label=item.logName||item.name,old=products.get(label)||{qty:0,total:0};old.qty++;old.total+=item.amount;products.set(label,old)}));
  document.querySelector('#sales-summary').innerHTML=products.size?[...products.entries()].sort((a,b)=>b[1].qty-a[1].qty).map(([name,data])=>`<li><span>${name}</span><b>${data.qty} · ${format(data.total)}</b></li>`).join(''):'<li class="empty">Aucune vente</li>';
  document.querySelector('#order-history').innerHTML=savedOrders.length?savedOrders.slice(0,50).map(order=>{const grouped=new Map();order.items.forEach(item=>{const label=item.logName||item.name;grouped.set(label,(grouped.get(label)||0)+1)});const detail=[...grouped.entries()].map(([name,qty])=>`${qty} × ${name}`).join(', ');return `<li><span class="history-icon">✓</span><span class="history-info"><b>${escapeHTML(detail)}</b><small>${order.source==='ardoise'?'Ardoise · ':''}${escapeHTML(order.operator||'Sans nom')} · ${new Date(order.date).toLocaleString('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small></span><span class="history-amount">${format(order.total)}</span>${order.source!=='ardoise'?`<button class="log-delete" data-order-cancel="${order.date}" type="button" title="Annuler cette commande">×</button>`:''}</li>`}).join(''):'<li class="empty">Aucune commande enregistrée</li>';
}
function renderTeamStats(){const admin=isAdminName(operatorName),html=teamStats.length?teamStats.map((person,index)=>`<div class="team-member"><span class="team-member-head"><b>${escapeHTML(person.name)}${isAdminName(person.name)?'<em class="team-admin-label">ADMIN</em>':''}</b>${admin&&person.name.toLowerCase()!==operatorName.toLowerCase()?`<button class="admin-reset-member" data-team-reset="${index}" type="button">Mettre à zéro</button>`:''}</span><div><span><small>Encaissé</small><strong>${format(person.revenue)}</strong></span><span><small>Articles</small><strong>${person.items}</strong></span><span><small>Commandes</small><strong>${person.orders}</strong></span></div></div>`).join(''):'<div class="team-empty">Aucun total partagé pour le moment</div>';document.querySelectorAll('.team-stats').forEach(container=>container.innerHTML=html)}
async function syncPersonalStats(revenue,items,orders){if(!db||!operatorName)return;await db.rpc('fermer_service_si_inactif');const{error}=await db.rpc('ajouter_stats_personnelles',{p_operator_name:operatorName,p_revenue:revenue,p_items:items,p_orders:orders});if(error)console.error('Stats équipe',error)}

function addToCart(amount,name,logName=name){ if(appMode==='tab'&&!requireName())return; cart.push({amount,name,logName}); renderCart(); toast(`${name} ajouté · total ${format(cart.reduce((s,x)=>s+x.amount,0))}`); }

function setAppMode(next){
  appMode=next; cart=[];
  document.body.classList.toggle('order-mode',appMode==='order');
  document.body.classList.toggle('expenses-mode',appMode==='expenses');
  document.body.classList.toggle('raffle-mode',appMode==='raffle');
  document.body.classList.toggle('gifts-mode',appMode==='gifts');
  document.body.classList.toggle('service-mode',appMode==='service');
  document.body.classList.toggle('games-mode',appMode==='games');
  document.querySelectorAll('[data-app-mode]').forEach(button=>button.classList.toggle('active',button.dataset.appMode===appMode));
  document.querySelector('.section-heading small').textContent=appMode==='tab'?'Touchez pour ajouter au panier':'Calcule la commande sans toucher à l’ardoise';
  renderCart(); toast(appMode==='tab'?'Mode ardoise partagé':appMode==='order'?'Mode commande simple':appMode==='expenses'?'Suivi des dépenses':appMode==='gifts'?'Suivi des cadeaux':appMode==='service'?'Gestion du service':appMode==='raffle'?'Tombola partagée':'Classement des jeux');
}
document.querySelectorAll('[data-app-mode]').forEach(button=>button.addEventListener('click',()=>setAppMode(button.dataset.appMode)));
document.querySelector('#add-citizen-sale').addEventListener('click',()=>{citizenSales++;localStorage.setItem(CITIZEN_SALES_KEY,citizenSales);renderCitizenSales();toast(`Vente n°${citizenSales} ajoutée`)});
document.querySelector('#reset-citizen-sales').addEventListener('click',()=>{if(citizenSales&&confirm('Remettre le compteur des ventes à zéro ?')){citizenSales=0;localStorage.setItem(CITIZEN_SALES_KEY,'0');renderCitizenSales();toast('Compteur remis à zéro')}});
document.querySelector('#theme-toggle').addEventListener('click',()=>{const next=document.body.classList.contains('theme-contrast')?'sand':'contrast';localStorage.setItem(THEME_KEY,next);applyTheme(next)});
document.querySelector('#sound-toggle').addEventListener('click',()=>{soundEnabled=!soundEnabled;localStorage.setItem(SOUND_KEY,soundEnabled?'on':'off');if(soundEnabled){try{alertAudioContext=alertAudioContext||new(window.AudioContext||window.webkitAudioContext)();alertAudioContext.resume();playRemoteSound()}catch{}}updateSoundButton();toast(soundEnabled?'Alertes sonores activées 🔔':'Alertes sonores coupées 🔕')});
document.querySelector('#remote-alert').addEventListener('click',()=>{const alert=document.querySelector('#remote-alert'),mode=alert.dataset.mode||'tab';alert.classList.remove('show');remoteAlertCount=0;setAppMode(mode);document.querySelector('.mode-switch').scrollIntoView({behavior:'smooth',block:'start'})});

async function refresh() {
  if (!db) { syncStatus('Configuration Supabase requise', 'error'); render(); return; }
  await db.rpc('fermer_service_si_inactif');
  const [balanceResult, logsResult, expensesResult,raffleSettingsResult,raffleEntriesResult,teamStatsResult,gameSettingsResult,gameScoresResult,gameLogsResult,gameWinnersResult,giftsResult,servicesResult,salesEventsResult,weeklyStatsResult] = await Promise.all([
    db.from('ardoise_state').select('balance,peak,updated_at').eq('id',1).single(),
    db.from('ardoise_logs').select('id,operation,amount,quantity,item_name,operator_name,created_at').order('created_at',{ascending:false}).limit(50),
    db.from('depenses').select('id,label,category,amount,operator_name,created_at').order('created_at',{ascending:false}).limit(100),
    db.from('tombola_settings').select('ticket_price,max_tickets,last_winner').eq('id',1).single(),
    db.from('tombola_entries').select('name,tickets,operator_name').order('created_at',{ascending:true}),
    db.from('stats_equipe').select('operator_name,revenue,items,orders').or('revenue.gt.0,items.gt.0,orders.gt.0').order('revenue',{ascending:false}),
    db.from('game_settings').select('title,game_type').eq('id',1).single(),
    db.from('game_scores').select('id,name,points'),
    db.from('game_point_logs').select('player_name,delta,operator_name,created_at').order('created_at',{ascending:false}).limit(50),
    db.from('game_winners').select('id,game_title,winner_name,points,second_name,second_points,third_name,third_points,standings,created_at').order('created_at',{ascending:false}).limit(3),
    db.from('gifts').select('id,beneficiary,phone,gift_type,quantity,remaining,amount,note,status,operator_name,created_at,completed_at').order('created_at',{ascending:false}).limit(100),
    db.from('bar_services').select('id,name,status,is_event,event_label,opened_at,opened_by,closed_at,closed_by,snapshot').order('opened_at',{ascending:false}).limit(50),
    db.from('sales_events').select('id,service_id,operator_name,revenue,items,orders,source,note,created_at').gte('created_at',getServiceWeek().start.toISOString()).order('created_at',{ascending:true}).limit(5000),
    db.rpc('obtenir_stats_hebdomadaires')
  ]);
  if (balanceResult.error || logsResult.error) { syncStatus('Connexion impossible', 'error'); toast('Vérifie la configuration Supabase'); return; }
  const row=balanceResult.data;
  state={ balance:Number(row.balance), peak:Number(row.peak), updated:new Date(row.updated_at).getTime(), history:logsResult.data.map(x=>({id:x.id,type:x.operation,amount:Number(x.amount),quantity:Number(x.quantity||1),name:x.item_name,operator:x.operator_name,date:new Date(x.created_at).getTime()})) };
  expenses=expensesResult.error?[]:expensesResult.data.map(x=>({id:x.id,label:x.label,category:x.category,amount:Number(x.amount),operator:x.operator_name,date:new Date(x.created_at).getTime()}));
  gifts=giftsResult.error?[]:giftsResult.data.map(x=>({id:x.id,name:x.beneficiary,phone:x.phone,type:x.gift_type,quantity:Number(x.quantity),remaining:Number(x.remaining),amount:Number(x.amount),note:x.note,status:x.status||'active',operator:x.operator_name,date:new Date(x.created_at).getTime(),completed:x.completed_at?new Date(x.completed_at).getTime():null}));
  if(!raffleSettingsResult.error&&!raffleEntriesResult.error){raffle={price:Number(raffleSettingsResult.data.ticket_price),max:Number(raffleSettingsResult.data.max_tickets),winner:raffleSettingsResult.data.last_winner,entries:raffleEntriesResult.data.map(x=>({name:x.name,tickets:Number(x.tickets),operator:x.operator_name}))}}
  teamStats=teamStatsResult.error?[]:teamStatsResult.data.map(x=>({name:x.operator_name,revenue:Number(x.revenue),items:Number(x.items),orders:Number(x.orders)}));
  if(!gameSettingsResult.error&&!gameScoresResult.error&&!gameLogsResult.error){game={title:gameSettingsResult.data.title,type:gameSettingsResult.data.game_type,scores:gameScoresResult.data.map(x=>({id:x.id,name:x.name,points:Number(x.points)})),logs:gameLogsResult.data.map(x=>({player:x.player_name,delta:Number(x.delta),operator:x.operator_name,date:new Date(x.created_at).getTime()})),winners:gameWinnersResult.error?[]:gameWinnersResult.data.map(x=>({id:x.id,title:x.game_title,first:{name:x.winner_name,points:Number(x.points)},second:{name:x.second_name,points:Number(x.second_points||0)},third:{name:x.third_name,points:Number(x.third_points||0)},standings:Array.isArray(x.standings)?x.standings.map(player=>({name:player.name,points:Number(player.points)})):[],date:new Date(x.created_at).getTime()})),winnersError:Boolean(gameWinnersResult.error)}}
  services=servicesResult.error?{current:null,history:[]}:{current:servicesResult.data.filter(x=>x.status==='open').map(x=>({id:x.id,name:x.name,isEvent:x.is_event,eventLabel:x.event_label,openedAt:x.opened_at,openedBy:x.opened_by}))[0]||null,history:servicesResult.data.filter(x=>x.status==='closed').map(x=>({id:x.id,name:x.name,isEvent:x.is_event,eventLabel:x.event_label,closedAt:x.closed_at,closedBy:x.closed_by,snapshot:x.snapshot}))};
  salesEvents=salesEventsResult.error?[]:salesEventsResult.data.map(x=>({id:x.id,serviceId:x.service_id,name:x.operator_name,revenue:Number(x.revenue),items:Number(x.items),orders:Number(x.orders),source:x.source,note:x.note,date:new Date(x.created_at).getTime()}));
  weeklyStats=weeklyStatsResult.error?[]:(weeklyStatsResult.data||[]).map(x=>({weekStart:x.week_start,day:Number(x.day),name:x.operator_name,revenue:Number(x.revenue),items:Number(x.items),orders:Number(x.orders)}));
  syncStatus('Ardoise partagée · en direct','online'); render();renderExpenses();renderGifts();renderRaffle();renderTeamStats();renderOrderLogs();renderGame();renderPreviousWinners();renderServices();
}

async function addTransaction(type, amount, name) {
  if (!requireName()) return;
  if (!db) return toast('Branche d’abord la base Supabase');
  if (type==='payment' && amount>state.balance) return toast(`Solde insuffisant : il reste ${format(state.balance)}`);
  const { error }=await db.rpc('appliquer_operation',{p_operation:type,p_amount:amount,p_item_name:name,p_operator_name:operatorName});
  if (error) return toast(error.message.includes('Solde insuffisant')?'Le solde vient de changer : montant insuffisant':'Opération non enregistrée');
  await refresh(); toast(type==='add'?`${format(amount)} ajoutés par ${operatorName} 🌺`:`${name} · − ${format(amount)} ✓`);
}

function updateMenuPrices(){
  document.querySelectorAll('.product[data-normal]').forEach(button=>{const price=happyHour&&button.dataset.happy?button.dataset.happy:button.dataset.normal;button.dataset.price=price;button.querySelector('strong').textContent=price});
  const dynamic=document.querySelectorAll('.dynamic-price');if(dynamic[0])dynamic[0].textContent=happyHour?'350':'450';if(dynamic[1])dynamic[1].textContent=happyHour?'300':'400';
  const toggle=document.querySelector('#happy-toggle');toggle.classList.toggle('active',happyHour);toggle.setAttribute('aria-pressed',happyHour);document.querySelector('#happy-state').textContent=happyHour?'Happy hour · 21h–22h':'Prix classiques';
}
document.querySelector('#happy-toggle').addEventListener('click',()=>{happyHour=!happyHour;updateMenuPrices();toast(happyHour?'Happy hour activé 🌅':'Prix classiques activés')});
document.querySelectorAll('[data-menu-view]').forEach(button=>button.addEventListener('click',()=>{const detailed=button.dataset.menuView==='detailed';document.querySelector('#simple-menu').hidden=detailed;document.querySelector('#detailed-menu').hidden=!detailed;document.querySelectorAll('[data-menu-view]').forEach(item=>item.classList.toggle('active',item===button))}));
document.querySelectorAll('.product').forEach(button=>button.addEventListener('click',()=>addToCart(Number(button.dataset.price),button.dataset.name,button.dataset.logName||button.dataset.name)));
document.querySelector('#custom-form').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#custom-amount');const amount=parseAmount(input.value);if(!Number.isFinite(amount)||amount<=0)return toast('Entre un montant libre supérieur à zéro');addToCart(amount,'Montant libre');input.value=''});
document.querySelector('#undo-item').addEventListener('click',()=>{const item=cart.pop();renderCart();if(item)toast(`${item.name} retiré du panier`)});
document.querySelector('#clear-cart').addEventListener('click',()=>{cart=[];renderCart();toast('Panier vidé')});
const orderChoiceModal=document.querySelector('#order-choice-modal');
async function completeSimpleOrder(){const total=cart.reduce((s,x)=>s+x.amount,0);savedOrders.unshift({total,items:cart.slice(),operator:operatorName,date:Date.now()});if(savedOrders.length>200)savedOrders.length=200;saveOrders();await syncPersonalStats(total,cart.length,1);cart=[];renderCart();await refresh();toast(`Commande de ${format(total)} encaissée ✓`)}
async function completeTabOrder(){
  const total=cart.reduce((s,x)=>s+x.amount,0);
  if(!requireName()||!db){if(!db)toast('Branche d’abord la base Supabase');return}
  if(total>state.balance)return toast(`Total ${format(total)} · il reste seulement ${format(state.balance)}`);
  await db.rpc('fermer_service_si_inactif');
  const pending=cart.map(item=>({...item,name:item.logName||item.name})); document.querySelector('#validate-cart').disabled=true;
  const {error}=await db.rpc('appliquer_panier',{p_items:pending,p_operator_name:operatorName});
  if(error){renderCart();return toast(error.message.includes('Solde insuffisant')?'Le solde vient de changer : total insuffisant':'Panier non enregistré')}
  savedOrders.unshift({total,items:cart.slice(),operator:operatorName,date:Date.now(),source:'ardoise'});if(savedOrders.length>200)savedOrders.length=200;saveOrders();
  cart=[];renderCart();await refresh();toast(`Panier de ${format(total)} validé ✓`);
}
document.querySelector('#validate-cart').addEventListener('click',async()=>{
  if(!cart.length)return;
  const total=cart.reduce((s,x)=>s+x.amount,0);
  if(appMode==='order'){
    if(!requireName())return;
    if(state.balance>0){document.querySelector('#choice-balance').textContent=format(state.balance);document.querySelector('#choice-order-total').textContent=format(total);const transfer=document.querySelector('#transfer-order-tab'),possible=Boolean(db)&&total<=state.balance;transfer.disabled=!possible;document.querySelector('#transfer-order-note').textContent=possible?'Le transfert déduira automatiquement la commande de l’ardoise.':total>state.balance?'Transfert impossible : la commande dépasse le montant restant sur l’ardoise.':'Transfert impossible : Supabase n’est pas connecté.';orderChoiceModal.showModal();return}
    await completeSimpleOrder();return
  }
  await completeTabOrder();
});
document.querySelector('#close-order-choice').addEventListener('click',()=>orderChoiceModal.close());
document.querySelector('#cancel-order-choice').addEventListener('click',()=>orderChoiceModal.close());
orderChoiceModal.addEventListener('click',event=>{if(event.target===orderChoiceModal)orderChoiceModal.close()});
document.querySelector('#confirm-simple-order').addEventListener('click',async()=>{orderChoiceModal.close();await completeSimpleOrder()});
document.querySelector('#transfer-order-tab').addEventListener('click',async()=>{orderChoiceModal.close();await completeTabOrder()});
const addModal=document.querySelector('#add-modal');
document.querySelector('#open-add').addEventListener('click',()=>{ if(!requireName())return; addModal.showModal(); setTimeout(()=>document.querySelector('#add-amount').focus(),50); });
document.querySelector('#close-add').addEventListener('click',()=>addModal.close());
addModal.addEventListener('click',e=>{if(e.target===addModal)addModal.close()});
document.querySelector('#add-form').addEventListener('submit',async e=>{ e.preventDefault(); const input=document.querySelector('#add-amount'); const amount=parseAmount(input.value); if(!Number.isFinite(amount)||amount<=0)return toast('Entre un montant supérieur à zéro'); addModal.close(); input.value=''; await addTransaction('add',amount,'Ajout à l’ardoise'); });

const nameModal=document.querySelector('#name-modal');
function openName(){ document.querySelector('#name-input').value=operatorName; nameModal.showModal(); setTimeout(()=>document.querySelector('#name-input').focus(),50); }
document.querySelector('#open-name').addEventListener('click',openName);
document.querySelector('#close-name').addEventListener('click',()=>nameModal.close());
document.querySelector('#name-form').addEventListener('submit',e=>{ e.preventDefault(); const value=document.querySelector('#name-input').value.trim(); if(!value)return; operatorName=value.slice(0,30); localStorage.setItem(NAME_KEY,operatorName); nameModal.close(); render();renderGifts();renderPreviousWinners(); toast(`Bienvenue ${operatorName} !`); });

const accessModal=document.querySelector('#access-modal'),changeAccessModal=document.querySelector('#change-access-modal');
function openAccessGate(){if(!db||sessionStorage.getItem(ACCESS_KEY)==='yes')return;document.body.classList.add('access-locked');accessModal.showModal();setTimeout(()=>document.querySelector('#access-password').focus(),50)}
accessModal.addEventListener('cancel',event=>event.preventDefault());
document.querySelector('#access-form').addEventListener('submit',async event=>{event.preventDefault();if(!db)return;const input=document.querySelector('#access-password'),button=document.querySelector('#access-submit'),error=document.querySelector('#access-error');button.disabled=true;error.textContent='Vérification…';const{data, error:rpcError}=await db.rpc('verifier_acces_application',{p_password:input.value});button.disabled=false;if(rpcError){error.textContent=rpcError.message.includes('schema cache')?'Installe d’abord le script du mot de passe dans Supabase.':rpcError.message;return}if(!data){error.textContent='Mot de passe incorrect';input.select();return}sessionStorage.setItem(ACCESS_KEY,'yes');input.value='';error.textContent='';document.body.classList.remove('access-locked');accessModal.close();toast('Accès autorisé 🌴');if(!operatorName)setTimeout(openName,200)});
document.querySelector('#open-access-settings').addEventListener('click',()=>{if(!isAdminName(operatorName))return;changeAccessModal.showModal();setTimeout(()=>document.querySelector('#current-access-password').focus(),50)});
document.querySelector('#close-access-settings').addEventListener('click',()=>changeAccessModal.close());
document.querySelector('#change-access-form').addEventListener('submit',async event=>{event.preventDefault();if(!db||!isAdminName(operatorName))return toast('Action réservée à Kai et Summer');const current=document.querySelector('#current-access-password').value,next=document.querySelector('#new-access-password').value,confirmPassword=document.querySelector('#confirm-access-password').value;if(next.length<6)return toast('Le nouveau mot de passe doit contenir au moins 6 caractères');if(next!==confirmPassword)return toast('Les deux nouveaux mots de passe sont différents');const{error}=await db.rpc('changer_mot_de_passe_application',{p_operator_name:operatorName,p_current_password:current,p_new_password:next});if(error)return toast(error.message);event.target.reset();changeAccessModal.close();toast('Mot de passe d’accès modifié ✓')});

document.querySelector('#reset').addEventListener('click',async()=>{ if(!requireName()||!db)return; if(confirm('Remettre l’ardoise partagée et tous ses logs à zéro ?')){ const {error}=await db.rpc('remettre_ardoise_a_zero'); if(error){console.error(error);return toast(`Remise à zéro impossible : ${error.message}`)} await refresh(); toast('Ardoise remise à zéro'); } });
document.querySelector('#expense-form').addEventListener('submit',async e=>{
  e.preventDefault();if(!requireName()||!db){if(!db)toast('Branche d’abord la base Supabase');return}
  const label=document.querySelector('#expense-label').value.trim(),category=document.querySelector('#expense-category').value,amount=parseAmount(document.querySelector('#expense-amount').value);
  if(!label||!Number.isFinite(amount)||amount<=0)return toast('Indique un achat et un montant valide');
  const {error}=await db.rpc('ajouter_depense',{p_label:label,p_category:category,p_amount:amount,p_operator_name:operatorName});
  if(error)return toast(`Dépense non enregistrée : ${error.message}`);
  e.target.reset();await refresh();toast(`Dépense de ${format(amount)} enregistrée ✓`);
});
document.querySelector('#reset-expenses').addEventListener('click',async()=>{
  if(!requireName()||!db)return;if(!confirm('Effacer tout l’historique des dépenses ?'))return;
  const {error}=await db.rpc('remettre_depenses_a_zero');if(error)return toast(`Remise à zéro impossible : ${error.message}`);await refresh();toast('Dépenses remises à zéro');
});
document.querySelector('#expense-history').addEventListener('click',async event=>{const button=event.target.closest('[data-expense-delete]');if(!button||!db)return;const item=expenses.find(x=>String(x.id)===button.dataset.expenseDelete);if(!item||!confirm(`Annuler la dépense « ${item.label} » de ${format(item.amount)} ?`))return;const{error}=await db.rpc('annuler_depense',{p_expense_id:item.id,p_requester_name:operatorName});if(error)return toast(error.message);await refresh();toast('Dépense annulée et rapport corrigé')});
document.querySelector('#gift-type').addEventListener('change',event=>{const money=event.target.value==='money',input=document.querySelector('#gift-value');document.querySelector('#gift-value-label').textContent=money?'Montant offert':'Nombre de consommations';input.step=money?'0.01':'1';input.inputMode=money?'decimal':'numeric'});
function resetGiftForm(){editingGiftId=null;document.querySelector('#gift-form').reset();document.querySelector('#gift-value').value=1;document.querySelector('#gift-type').dispatchEvent(new Event('change'));document.querySelector('#gift-submit').textContent='🎁 Enregistrer le cadeau';document.querySelector('#gift-edit-cancel').hidden=true}
document.querySelector('#gift-edit-cancel').addEventListener('click',resetGiftForm);
document.querySelector('#gift-form').addEventListener('submit',async event=>{event.preventDefault();if(!requireName()||!db)return;const name=document.querySelector('#gift-name').value.trim(),phone=document.querySelector('#gift-phone').value.trim(),type=document.querySelector('#gift-type').value,value=parseAmount(document.querySelector('#gift-value').value),note=document.querySelector('#gift-note').value.trim();if(!name||!Number.isFinite(value)||value<=0||type==='drink'&&!Number.isInteger(value))return toast('Vérifie le nom et la quantité');const values={beneficiary:name.slice(0,50),phone:phone.slice(0,30)||null,gift_type:type,quantity:type==='drink'?value:0,remaining:type==='drink'?value:0,amount:type==='money'?value:0,note:note.slice(0,80),status:'active',completed_at:null,updated_at:new Date().toISOString()},result=editingGiftId?await db.from('gifts').update(values).eq('id',editingGiftId):await db.from('gifts').insert({...values,operator_name:operatorName.slice(0,30)});if(result.error)return toast(`Cadeau non enregistré : ${result.error.message}`);const edited=Boolean(editingGiftId);resetGiftForm();await refresh();toast(edited?`Cadeau de ${name} modifié ✓`:`Cadeau ajouté pour ${name} 🎁`)});
async function handleGiftClick(event){const use=event.target.closest('[data-gift-use]'),edit=event.target.closest('[data-gift-edit]'),finish=event.target.closest('[data-gift-finish]'),remove=event.target.closest('[data-gift-delete]');if(use){if(!requireName()||!db)return;use.disabled=true;const{error}=await db.rpc('utiliser_conso_cadeau',{p_gift_id:Number(use.dataset.giftUse),p_operator_name:operatorName});if(error){use.disabled=false;return toast(error.message)}await refresh();toast('Une consommation gratuite utilisée ✓');return}if(edit){const item=gifts.find(x=>String(x.id)===edit.dataset.giftEdit);if(!item)return;editingGiftId=item.id;document.querySelector('#gift-name').value=item.name;document.querySelector('#gift-phone').value=item.phone||'';document.querySelector('#gift-type').value=item.type;document.querySelector('#gift-value').value=item.type==='drink'?item.remaining:item.amount;document.querySelector('#gift-note').value=item.note||'';document.querySelector('#gift-type').dispatchEvent(new Event('change'));document.querySelector('#gift-submit').textContent='✓ Enregistrer les modifications';document.querySelector('#gift-edit-cancel').hidden=false;document.querySelector('.gift-form-card').scrollIntoView({behavior:'smooth',block:'start'});return}if(finish){if(!confirm('Marquer ce cadeau comme terminé et le déplacer dans l’historique ?'))return;const{error}=await db.from('gifts').update({status:'completed',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',Number(finish.dataset.giftFinish));if(error)return toast(error.message);await refresh();toast('Cadeau déplacé dans l’historique');return}if(remove){if(!isAdminName(operatorName)||!db)return;const item=gifts.find(x=>String(x.id)===remove.dataset.giftDelete);if(!item||!confirm(`Supprimer définitivement le cadeau de ${item.name} ?`))return;const{error}=await db.rpc('supprimer_cadeau',{p_gift_id:item.id,p_requester_name:operatorName});if(error)return toast(error.message);await refresh();toast('Cadeau supprimé')}}
document.querySelector('#gift-list').addEventListener('click',handleGiftClick);document.querySelector('#gift-history').addEventListener('click',handleGiftClick);
async function handleGiftRestore(event){const button=event.target.closest('[data-gift-restore]');if(!button||!db)return;const item=gifts.find(x=>String(x.id)===button.dataset.giftRestore);if(!item)return;const next=Math.min(item.quantity,item.remaining+1),{error}=await db.from('gifts').update({remaining:next,status:'active',completed_at:null,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)return toast(error.message);await refresh();toast('Consommation restaurée ✓')}
document.querySelector('#gift-list').addEventListener('click',handleGiftRestore);document.querySelector('#gift-history').addEventListener('click',handleGiftRestore);
document.querySelector('#reset-gifts').addEventListener('click',async()=>{if(!isAdminName(operatorName)||!db)return;if(!confirm('ATTENTION : supprimer définitivement TOUS les cadeaux et toutes les consommations restantes ?'))return;const{error}=await db.rpc('admin_supprimer_tous_cadeaux',{p_requester_name:operatorName});if(error)return toast(error.message);await refresh();toast('Tous les cadeaux ont été supprimés')});
document.querySelector('#service-event').addEventListener('change',event=>{document.querySelector('#service-event-name').hidden=!event.target.checked;if(!event.target.checked)document.querySelector('#service-event-name').value=''});
document.querySelector('#open-service-form').addEventListener('submit',async event=>{event.preventDefault();if(!requireName()||!db)return;const isEvent=document.querySelector('#service-event').checked,eventName=document.querySelector('#service-event-name').value.trim(),name=`${getAutomaticServiceName()}${isEvent&&eventName?` · ${eventName}`:''}`;const{error}=await db.rpc('ouvrir_service',{p_name:name,p_operator_name:operatorName,p_is_event:isEvent,p_event_label:eventName||null});if(error)return toast(error.message);event.target.reset();document.querySelector('#service-event-name').hidden=true;await refresh();toast('Service ouvert 🟢')});
document.querySelector('#close-service').addEventListener('click',async()=>{if(!requireName()||!db||!services.current)return;const message=isAdminName(operatorName)?`Fermer « ${services.current.name} », sauvegarder son rapport et remettre les statistiques du service à zéro ?`:`Fermer « ${services.current.name} » ?`;if(!confirm(message))return;const{error}=await db.rpc('fermer_service',{p_operator_name:operatorName});if(error)return toast(error.message);savedOrders=[];saveOrders();await refresh();toast('Service fermé ✓')});
document.querySelector('#export-service-csv').addEventListener('click',downloadServiceCSV);
document.querySelector('#week-selector').addEventListener('change',event=>{selectedWeek=event.target.value;renderServices()});
document.querySelector('#seller-pie-legend').addEventListener('click',event=>{const button=event.target.closest('[data-pie-index]');if(!button)return;const seller=weeklyPieSellers[Number(button.dataset.pieIndex)];if(!seller)return;document.querySelector('#seller-pie-value').textContent=format(seller.value);document.querySelector('#seller-pie-name').textContent=seller.name;document.querySelectorAll('#seller-pie-legend button').forEach(item=>item.classList.toggle('active',item===button))});
document.querySelector('#service-adjust-form').addEventListener('submit',async event=>{event.preventDefault();if(!db||!isAdminName(operatorName))return toast('Action réservée à Kai et Summer');const target=document.querySelector('#adjust-person').value.trim(),operation=document.querySelector('#adjust-operation').value,revenue=parseAmount(document.querySelector('#adjust-revenue').value)||0,items=Number(document.querySelector('#adjust-items').value)||0,orders=Number(document.querySelector('#adjust-orders').value)||0,note=document.querySelector('#adjust-note').value.trim();if(!target||revenue<0||items<0||orders<0||!Number.isInteger(items)||!Number.isInteger(orders)||revenue+items+orders<=0)return toast('Indique un nom et au moins une valeur à corriger');const{error}=await db.rpc('admin_ajuster_statistiques',{p_requester_name:operatorName,p_target_name:target,p_operation:operation,p_revenue:revenue,p_items:items,p_orders:orders,p_note:note||null});if(error)return toast(`Correction impossible : ${error.message}`);event.target.reset();document.querySelector('#adjust-revenue').value=0;document.querySelector('#adjust-items').value=0;document.querySelector('#adjust-orders').value=0;await refresh();toast(`Statistiques de ${target} corrigées ✓`)});
document.querySelector('#manual-adjustments').addEventListener('click',async event=>{const button=event.target.closest('[data-adjust-delete]');if(!button||!db||!isAdminName(operatorName))return;if(!confirm('Annuler cette correction manuelle et recalculer les statistiques ?'))return;const{error}=await db.rpc('admin_annuler_correction',{p_event_id:Number(button.dataset.adjustDelete),p_requester_name:operatorName});if(error)return toast(`Annulation impossible : ${error.message}`);await refresh();toast('Correction annulée et statistiques recalculées ✓')});
function openDayStats(offset){const base=selectedWeek==='current'?getServiceWeek().start:new Date(selectedWeek),date=new Date(base);date.setDate(date.getDate()+offset);date.setHours(21,0,0,0);selectedStatsDay=date;const rows=weeklyStats.filter(row=>row.weekStart===localDateKey(base)&&row.day===date.getDay()),sellers=aggregateSales(rows,row=>row.name||'Inconnu'),knownSellers=[...new Set(['Kai','Summer',...teamStats.map(person=>person.name),...weeklyStats.map(row=>row.name)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));document.querySelector('#day-stats-title').textContent=`${date.toLocaleDateString('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})} · 20 h à 20 h`;document.querySelector('#day-adjust-date').value=date.toISOString();document.querySelector('#day-adjust-person').innerHTML=`<option value="">Choisir un vendeur</option>${knownSellers.map(name=>`<option value="${escapeHTML(name)}">${escapeHTML(name)}${isAdminName(name)?' · ADMIN':''}</option>`).join('')}`;document.querySelector('#day-seller-recap').innerHTML=[...sellers.entries()].sort((a,b)=>b[1].revenue-a[1].revenue).map(([name,value])=>`<div class="week-seller"><b>${escapeHTML(name)}</b><div><span><small>Encaissé</small><strong>${format(value.revenue)}</strong></span><span><small>Articles</small><strong>${value.items}</strong></span><span><small>Commandes</small><strong>${value.orders}</strong></span></div></div>`).join('')||'<div class="team-empty">Aucune vente ce jour-là</div>';document.querySelector('#day-stats-modal').showModal()}
document.querySelector('#week-chart').addEventListener('click',event=>{const column=event.target.closest('[data-chart-key]');if(column&&isAdminName(operatorName))openDayStats(Number(column.dataset.chartKey))});
document.querySelector('#week-chart').addEventListener('keydown',event=>{const column=event.target.closest('[data-chart-key]');if(column&&(event.key==='Enter'||event.key===' ')){event.preventDefault();openDayStats(Number(column.dataset.chartKey))}});
document.querySelector('#close-day-stats').addEventListener('click',()=>document.querySelector('#day-stats-modal').close());
document.querySelector('#day-adjust-form').addEventListener('submit',async event=>{event.preventDefault();if(!db||!isAdminName(operatorName))return;const target=document.querySelector('#day-adjust-person').value.trim(),operation=document.querySelector('#day-adjust-operation').value,revenue=parseAmount(document.querySelector('#day-adjust-revenue').value)||0,items=Number(document.querySelector('#day-adjust-items').value)||0,orders=Number(document.querySelector('#day-adjust-orders').value)||0,note=document.querySelector('#day-adjust-note').value.trim(),effectiveAt=document.querySelector('#day-adjust-date').value;if(!target||revenue+items+orders<=0||!Number.isInteger(items)||!Number.isInteger(orders))return toast('Indique le vendeur et une valeur à corriger');const{error}=await db.rpc('admin_ajuster_statistiques_jour',{p_requester_name:operatorName,p_target_name:target,p_operation:operation,p_revenue:revenue,p_items:items,p_orders:orders,p_note:note||null,p_effective_at:effectiveAt});if(error)return toast(`Correction impossible : ${error.message}`);event.target.reset();document.querySelector('#day-stats-modal').close();await refresh();toast('Journée corrigée ✓')});
document.querySelector('#raffle-tickets').addEventListener('input',updateRaffleCost);
document.querySelector('#raffle-settings-form').addEventListener('submit',async e=>{e.preventDefault();if(!db)return toast('Branche d’abord la base Supabase');const price=parseAmount(document.querySelector('#ticket-price').value),max=Number(document.querySelector('#ticket-max').value);if(!Number.isFinite(price)||price<=0||!Number.isInteger(max)||max<1)return toast('Réglages de tombola invalides');const{error}=await db.rpc('configurer_tombola',{p_ticket_price:price,p_max_tickets:max});if(error)return toast(error.message);await refresh();toast('Réglages de la tombola enregistrés')});
document.querySelector('#raffle-entry-form').addEventListener('submit',async e=>{e.preventDefault();if(!requireName()||!db)return;const name=document.querySelector('#raffle-name').value.trim(),tickets=Number(document.querySelector('#raffle-tickets').value);if(!name||!Number.isInteger(tickets)||tickets<1)return toast('Participant ou tickets invalides');const{error}=await db.rpc('ajouter_tickets_tombola',{p_name:name,p_tickets:tickets,p_operator_name:operatorName});if(error)return toast(error.message);e.target.reset();document.querySelector('#raffle-tickets').value=1;await refresh();toast(`${tickets} ticket${tickets>1?'s':''} ajouté${tickets>1?'s':''} pour ${name}`)});
document.querySelector('#draw-winner').addEventListener('click',async()=>{if(!db)return;if(!confirm('Lancer le tirage au sort maintenant ?'))return;const{data,error}=await db.rpc('tirer_gagnant_tombola');if(error)return toast(error.message);await refresh();toast(`🏆 ${data} gagne la tombola !`)});
document.querySelector('#reset-raffle').addEventListener('click',async()=>{if(!db||!confirm('Effacer tous les participants et le gagnant ?'))return;const{error}=await db.rpc('remettre_tombola_a_zero');if(error)return toast(error.message);await refresh();toast('Tombola remise à zéro')});
document.querySelector('#game-settings-form').addEventListener('submit',async event=>{event.preventDefault();if(!db)return toast('Branche d’abord la base Supabase');const title=document.querySelector('#game-title').value.trim(),type=document.querySelector('#game-type').value;if(!title)return toast('Le nom de la partie est obligatoire');const{error}=await db.rpc('configurer_jeu',{p_title:title,p_game_type:type});if(error)return toast(error.message);await refresh();toast('Partie enregistrée')});
document.querySelector('#game-player-form').addEventListener('submit',async event=>{event.preventDefault();if(!db)return toast('Branche d’abord la base Supabase');const input=document.querySelector('#game-player-name'),name=input.value.trim();if(!name)return;const{error}=await db.rpc('ajouter_joueur',{p_name:name});if(error)return toast(error.message);input.value='';await refresh();toast(`${name} ajouté au classement`)});
document.querySelector('#add-previous-players').addEventListener('click',async()=>{if(!db)return toast('Branche d’abord la base Supabase');const previous=game.winners[0]?.standings||[];if(!previous.length)return toast('Aucune liste précédente disponible');const existing=new Set(game.scores.map(x=>x.name.trim().toLowerCase())),names=previous.map(x=>String(x.name||'').trim()).filter(name=>name&&!existing.has(name.toLowerCase()));if(!names.length)return toast('Tous les participants précédents sont déjà présents');const button=document.querySelector('#add-previous-players');button.disabled=true;let added=0;for(const name of names){const{error}=await db.rpc('ajouter_joueur',{p_name:name});if(!error)added++}button.disabled=false;await refresh();toast(added?`${added} participant${added>1?'s':''} ajouté${added>1?'s':''} depuis la partie précédente`:'Aucun participant n’a pu être ajouté')});
document.querySelector('#game-sort').addEventListener('change',event=>{gameSort=event.target.value;localStorage.setItem(GAME_SORT_KEY,gameSort);renderGame()});
document.querySelector('#previous-winners').addEventListener('click',async event=>{const button=event.target.closest('[data-delete-game]');if(!button||!db||!isAdminName(operatorName))return;if(!confirm('Supprimer cette partie finalisée de l’historique ?'))return;const{error}=await db.rpc('admin_supprimer_partie_archivee',{p_winner_id:Number(button.dataset.deleteGame),p_requester_name:operatorName});if(error)return toast(error.message);await refresh();toast('Partie supprimée de l’historique')});
document.querySelector('#leaderboard').addEventListener('click',async event=>{const scoreButton=event.target.closest('[data-score-id]'),deleteButton=event.target.closest('[data-delete-score]');if(scoreButton){if(!requireName()||!db)return;scoreButton.disabled=true;const{error}=await db.rpc('modifier_points_jeu',{p_score_id:Number(scoreButton.dataset.scoreId),p_delta:Number(scoreButton.dataset.delta),p_operator_name:operatorName});if(error){scoreButton.disabled=false;return toast(error.message)}await refresh();return}if(deleteButton){if(!db)return;const player=game.scores.find(x=>String(x.id)===deleteButton.dataset.deleteScore);if(!player||!confirm(`Supprimer ${player.name} du classement ?`))return;const{error}=await db.rpc('supprimer_joueur',{p_score_id:player.id});if(error)return toast(error.message);await refresh();toast(`${player.name} supprimé`)}});
document.querySelector('#reset-game').addEventListener('click',async()=>{if(!db)return;const title=document.querySelector('#game-title').value.trim(),type=document.querySelector('#game-type').value;if(!title){document.querySelector('#game-title').focus();return toast('Donne obligatoirement un nom à la partie')};if(!game.scores.length)return toast('Ajoute au moins un participant');if(!confirm(`Finaliser et sauvegarder « ${title} » ? Le podium sera enregistré et le classement remis à zéro.`))return;const settingsResult=await db.rpc('configurer_jeu',{p_title:title,p_game_type:type});if(settingsResult.error)return toast(`Nom non enregistré : ${settingsResult.error.message}`);const{error}=await db.rpc('nouvelle_partie_jeu');if(error)return toast(`Sauvegarde impossible : ${error.message}`);await refresh();toast(`« ${title} » sauvegardée avec son podium`)});
document.querySelector('#reset-game-winners').addEventListener('click',async()=>{if(!db||!isAdminName(operatorName))return toast('Action réservée à Kai et Summer');if(!confirm('ATTENTION : supprimer définitivement TOUT l’historique des parties et TOUS les derniers gagnants ?'))return;const{error}=await db.rpc('admin_supprimer_historique_jeux',{p_requester_name:operatorName});if(error)return toast(`Suppression impossible : ${error.message}`);await refresh();toast('Tout l’historique des jeux a été supprimé')});
document.querySelector('#reset-orders').addEventListener('click',async()=>{if(!requireName())return;if(confirm('Effacer tes commandes locales et tes totaux partagés ?')){savedOrders=[];saveOrders();if(db){const{error}=await db.rpc('remettre_stats_personnelles_a_zero',{p_operator_name:operatorName});if(error)console.error(error);await refresh()}toast('Tes statistiques ont été remises à zéro')}});
document.querySelector('#order-history').addEventListener('click',async event=>{const button=event.target.closest('[data-order-cancel]');if(!button||!db)return;const index=savedOrders.findIndex(order=>String(order.date)===button.dataset.orderCancel);if(index<0)return;const order=savedOrders[index];if(!confirm(`Annuler cette commande de ${format(order.total)} ? Les totaux seront corrigés.`))return;const{error}=await db.rpc('annuler_commande_simple',{p_operator_name:order.operator||operatorName,p_revenue:order.total,p_items:order.items.length});if(error)return toast(error.message);savedOrders.splice(index,1);saveOrders();await refresh();toast('Commande annulée et totaux corrigés')});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-team-reset]');if(!button||!isAdminName(operatorName)||!db)return;const person=teamStats[Number(button.dataset.teamReset)];if(!person||!confirm(`Remettre les totaux de ${person.name} à zéro ?`))return;const{error}=await db.rpc('admin_remettre_stats_a_zero',{p_requester_name:operatorName,p_target_name:person.name});if(error)return toast(error.message);await refresh();toast(`Totaux de ${person.name} remis à zéro`)});
document.querySelector('#history').addEventListener('click',async event=>{const button=event.target.closest('[data-log-delete]');if(!button||!db)return;const item=state.history.find(row=>String(row.id)===button.dataset.logDelete);if(!item||!confirm(`Annuler « ${item.quantity>1?item.quantity+' × ':''}${item.name} » ? Le montant sera remis sur l’ardoise.`))return;button.disabled=true;const{error}=await db.rpc('annuler_ligne_ardoise',{p_log_id:item.id,p_requester_name:operatorName});if(error){button.disabled=false;return toast(error.message)}await refresh();toast('Ligne annulée et totaux corrigés')});
if(db){ db.channel('mojito-inn-live').on('postgres_changes',{event:'*',schema:'public',table:'ardoise_state'},refresh).on('postgres_changes',{event:'INSERT',schema:'public',table:'ardoise_logs'},payload=>{showRemoteAlert(payload.new);refresh()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'ardoise_logs'},refresh).on('postgres_changes',{event:'DELETE',schema:'public',table:'ardoise_logs'},refresh).on('postgres_changes',{event:'INSERT',schema:'public',table:'depenses'},payload=>{if(String(payload.new.operator_name).toLowerCase()!==operatorName.toLowerCase())showTeamAlert(`${payload.new.operator_name} a ajouté une dépense de ${format(payload.new.amount)}`,'addition','expenses');refresh()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'depenses'},refresh).on('postgres_changes',{event:'DELETE',schema:'public',table:'depenses'},refresh).on('postgres_changes',{event:'INSERT',schema:'public',table:'gifts'},payload=>{if(String(payload.new.operator_name).toLowerCase()!==operatorName.toLowerCase())showTeamAlert(`${payload.new.operator_name} a offert un cadeau à ${payload.new.beneficiary}`,'addition','gifts');refresh()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'gifts'},refresh).on('postgres_changes',{event:'DELETE',schema:'public',table:'gifts'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'tombola_settings'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'tombola_entries'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'stats_equipe'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'sales_events'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'game_settings'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'game_scores'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'game_point_logs'},refresh).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_winners'},payload=>{showTeamAlert(`Partie « ${payload.new.game_title} » finalisée`,'payment','games');refresh()}).on('postgres_changes',{event:'DELETE',schema:'public',table:'game_winners'},refresh).on('postgres_changes',{event:'INSERT',schema:'public',table:'bar_services'},payload=>{if(String(payload.new.opened_by).toLowerCase()!==operatorName.toLowerCase())showTeamAlert(`${payload.new.opened_by} a ouvert « ${payload.new.name} »`,'payment','service');refresh()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'bar_services'},payload=>{if(payload.new.status==='closed'){if(String(payload.new.closed_by).toLowerCase()!==operatorName.toLowerCase())showTeamAlert(`${payload.new.closed_by} a fermé « ${payload.new.name} »`,'addition','service');savedOrders=[];saveOrders()}refresh()}).subscribe(status=>{if(status==='SUBSCRIBED')syncStatus('Ardoise partagée · en direct','online')}); }
if(db){db.channel('mojito-balance-alerts').on('postgres_changes',{event:'UPDATE',schema:'public',table:'ardoise_state'},payload=>{const next=Number(payload.new.balance);if(state.balance>0&&next===0)showTeamAlert('L’ardoise est arrivée à zéro ✓','payment','tab');else if(state.balance>500&&next>0&&next<=500)showTeamAlert(`Ardoise bientôt vide · ${format(next)} restants`,'addition','tab')}).subscribe()}
updateMenuPrices();applyTheme(localStorage.getItem(THEME_KEY)||'sand');updateSoundButton();render(); renderCart();renderExpenses();renderGifts();renderOrderLogs();renderRaffle();renderCitizenSales();renderTeamStats();renderGame();renderPreviousWinners();renderServices(); refresh();setInterval(()=>{if(services.current)renderServices()},60000);setInterval(async()=>{if(db){const{data}=await db.rpc('fermer_service_si_inactif');if(data){await refresh();toast('Service fermé automatiquement après 4 h sans vente')}}},300000);openAccessGate();if((!db||sessionStorage.getItem(ACCESS_KEY)==='yes')&&!operatorName)setTimeout(openName,250);
