-- Crée d’abord kai@staff.mojito-inn.fr et summer@staff.mojito-inn.fr dans Authentication > Users.
create table if not exists public.employee_profiles(user_id uuid primary key references auth.users(id)on delete cascade,username text not null unique,display_name text not null,role text not null default'employee'check(role in('employee','admin')),active boolean not null default true,created_at timestamptz not null default now(),last_seen_at timestamptz);
alter table public.employee_profiles enable row level security;revoke all on public.employee_profiles from anon,authenticated;grant select on public.employee_profiles to authenticated;
drop policy if exists "Employé lit son profil"on public.employee_profiles;create policy "Employé lit son profil"on public.employee_profiles for select to authenticated using(user_id=auth.uid());
insert into public.employee_profiles(user_id,username,display_name,role)select id,lower(split_part(email,'@',1)),initcap(split_part(email,'@',1)),case when lower(split_part(email,'@',1))in('kai','summer')then'admin'else'employee'end from auth.users where email like'%@staff.mojito-inn.fr'on conflict(user_id)do update set username=excluded.username,display_name=excluded.display_name,role=excluded.role;
create or replace function public.liste_employes_connexion()returns table(username text,display_name text)language sql stable security definer set search_path=public as $$select p.username,p.display_name from employee_profiles p where p.active order by p.display_name$$;grant execute on function public.liste_employes_connexion()to anon,authenticated;
create or replace function public.mon_profil_employe()returns jsonb language plpgsql security definer set search_path=public as $$declare p employee_profiles%rowtype;begin select*into p from employee_profiles where user_id=auth.uid()and active;if not found then raise exception'Compte employé absent ou désactivé';end if;update employee_profiles set last_seen_at=now()where user_id=p.user_id;return jsonb_build_object('username',p.username,'display_name',p.display_name,'role',p.role);end;$$;grant execute on function public.mon_profil_employe()to authenticated;
create or replace function public.est_admin_mojito()returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from employee_profiles where user_id=auth.uid()and active and role='admin')$$;grant execute on function public.est_admin_mojito()to authenticated;
create or replace function public.lire_controle_equipe(p_requester_name text,p_week_start timestamptz)returns table(id bigint,sale_id uuid,service_id bigint,service_name text,operator_name text,source text,action text,item_name text,quantity integer,unit_amount numeric,total_amount numeric,created_at timestamptz)language plpgsql stable security definer set search_path=public as $$begin if not public.est_admin_mojito()then raise exception'Action réservée aux administrateurs';end if;return query select a.id,a.sale_id,a.service_id,s.name,a.operator_name,a.source,a.action,a.item_name,a.quantity,a.unit_amount,a.total_amount,a.created_at from team_audit_logs a left join bar_services s on s.id=a.service_id where a.created_at>=p_week_start and a.created_at<p_week_start+interval'7 days'order by a.created_at desc,a.id desc;end;$$;grant execute on function public.lire_controle_equipe(text,timestamptz)to authenticated;revoke execute on function public.lire_controle_equipe(text,timestamptz)from anon;
notify pgrst,'reload schema';

