create table if not exists public.important_images (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 50),
  url text not null unique check (url ~ '^https?://'),
  is_fixed boolean not null default false,
  created_by text not null,
  created_at timestamptz not null default now()
);

alter table public.important_images enable row level security;

drop policy if exists "Lecture publique des images importantes" on public.important_images;
create policy "Lecture publique des images importantes"
on public.important_images for select
to anon, authenticated
using (true);

insert into public.important_images (title,url,is_fixed,created_by)
values
  ('Image d’ouverture','https://upload.storylife.fr/i/01KZXVZN3N70V85FB6RY335ET5.png',true,'Kai'),
  ('Menu du Mojito Inn','https://upload.storylife.fr/i/01KXGNHHSG51Y6DN61Y9K5RBJF.png',true,'Kai')
on conflict (url) do update set title=excluded.title,is_fixed=true;

create or replace function public.ajouter_image_importante(
  p_title text,
  p_url text,
  p_operator_name text
) returns bigint
language plpgsql security definer set search_path=public
as $$
declare new_id bigint;
begin
  if not public.est_admin_mojito() then raise exception 'Action réservée aux administrateurs'; end if;
  if nullif(trim(p_title),'') is null then raise exception 'Titre requis'; end if;
  if length(trim(p_title)) > 50 then raise exception 'Titre trop long'; end if;
  if trim(p_url) !~ '^https?://' then raise exception 'Lien invalide'; end if;
  insert into public.important_images(title,url,created_by)
  values(trim(p_title),trim(p_url),trim(p_operator_name))
  on conflict (url) do update set
    title=excluded.title,
    created_by=excluded.created_by
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.supprimer_image_importante(
  p_id bigint,
  p_operator_name text
) returns void
language plpgsql security definer set search_path=public
as $$
begin
  if nullif(trim(p_operator_name),'') is null then raise exception 'Nom requis'; end if;
  if exists(select 1 from public.important_images where id=p_id and is_fixed) then
    raise exception 'Cette image principale est protégée';
  end if;
  delete from public.important_images where id=p_id;
end;
$$;

grant select on public.important_images to anon, authenticated;
grant execute on function public.ajouter_image_importante(text,text,text) to anon, authenticated;
revoke execute on function public.supprimer_image_importante(bigint,text) from anon;
grant execute on function public.supprimer_image_importante(bigint,text) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='important_images'
  ) then
    alter publication supabase_realtime add table public.important_images;
  end if;
end $$;

