-- Sécurisation des identités, de la remise à zéro et du journal permanent.
-- À exécuter après les autres scripts dans Supabase > SQL Editor.

create or replace function public.nom_employe_connecte() returns text language plpgsql stable security definer set search_path=public as $$
declare v_name text;begin select left(trim(display_name),30)into v_name from employee_profiles where user_id=auth.uid()and active and approval_status='approved';if v_name is null then raise exception'Compte employé absent, en attente ou désactivé';end if;return v_name;end;$$;
revoke all on function public.nom_employe_connecte()from public,anon;grant execute on function public.nom_employe_connecte()to authenticated;

create or replace function public.exiger_admin_mojito()returns text language plpgsql stable security definer set search_path=public as $$
declare v_name text;begin select left(trim(display_name),30)into v_name from employee_profiles where user_id=auth.uid()and active and approval_status='approved'and role='admin';if v_name is null then raise exception'Action réservée aux administrateurs';end if;return v_name;end;$$;
revoke all on function public.exiger_admin_mojito()from public,anon;grant execute on function public.exiger_admin_mojito()to authenticated;

create or replace function public.ajouter_ardoise_nominative(p_amount numeric,p_debtor_name text,p_operator_name text,p_include_in_podium boolean)returns void language plpgsql security definer set search_path=public as $$
declare clean_operator text:=public.nom_employe_connecte();begin if p_amount is null or p_amount<=0 then raise exception'Montant invalide';end if;if nullif(trim(p_debtor_name),'')is null or length(trim(p_debtor_name))>50 then raise exception'Nom de la personne invalide';end if;update ardoise_state set balance=balance+p_amount,peak=greatest(peak,balance+p_amount),updated_at=now()where id=1;insert into ardoise_logs(operation,amount,quantity,item_name,operator_name,debtor_name,counts_for_podium)values('add',p_amount,1,'Ajout à l’ardoise',clean_operator,trim(p_debtor_name),coalesce(p_include_in_podium,true));insert into ardoise_people(name,normalized_name,updated_at)values(trim(p_debtor_name),lower(trim(p_debtor_name)),now())on conflict(normalized_name)do update set name=excluded.name,updated_at=now();end;$$;
create or replace function public.ajouter_ardoise_nominative(p_amount numeric,p_debtor_name text,p_operator_name text)returns void language plpgsql security definer set search_path=public as $$begin perform public.ajouter_ardoise_nominative(p_amount,p_debtor_name,public.nom_employe_connecte(),true);end;$$;

create or replace function public.appliquer_operation(p_operation text,p_amount numeric,p_item_name text,p_operator_name text)returns void language plpgsql security definer set search_path=public as $$
declare current_balance numeric;clean_operator text:=public.nom_employe_connecte();begin if p_operation not in('add','payment')or p_amount<=0 then raise exception'Opération invalide';end if;select balance into current_balance from ardoise_state where id=1 for update;if p_operation='payment'and p_amount>current_balance then raise exception'Solde insuffisant';end if;update ardoise_state set balance=balance+case when p_operation='add'then p_amount else-p_amount end,peak=case when p_operation='add'then greatest(peak,balance+p_amount)else peak end,updated_at=now()where id=1;insert into ardoise_logs(operation,amount,item_name,operator_name)values(p_operation,p_amount,left(coalesce(p_item_name,'Montant libre'),80),clean_operator);end;$$;

create or replace function public.appliquer_panier(p_items jsonb,p_operator_name text)returns void language plpgsql security definer set search_path=public as $$
declare total_amount numeric;current_balance numeric;basket_id uuid:=gen_random_uuid();current_service bigint;item_count integer;clean_name text:=public.nom_employe_connecte();begin if jsonb_typeof(p_items)<>'array'or jsonb_array_length(p_items)<1 or jsonb_array_length(p_items)>100 then raise exception'Panier invalide';end if;select coalesce(sum((x->>'amount')::numeric),0),count(*)into total_amount,item_count from jsonb_array_elements(p_items)x;if total_amount<=0 or exists(select 1 from jsonb_array_elements(p_items)x where(x->>'amount')::numeric<=0)then raise exception'Montant invalide';end if;select balance into current_balance from ardoise_state where id=1 for update;if total_amount>current_balance then raise exception'Solde insuffisant';end if;perform fermer_service_si_inactif();select id into current_service from bar_services where status='open'limit 1;if current_service is null then begin insert into bar_services(name,opened_by)values(nom_service_automatique(),clean_name)returning id into current_service;exception when unique_violation then select id into current_service from bar_services where status='open'limit 1;end;end if;insert into ardoise_logs(operation,amount,quantity,item_name,operator_name,sale_id)select'payment',unit_amount*qty,qty,left(item_label,80),clean_name,basket_id from(select(x->>'amount')::numeric unit_amount,coalesce(x->>'name','Montant libre')item_label,count(*)::integer qty from jsonb_array_elements(p_items)x group by 1,2)g;update ardoise_state set balance=balance-total_amount,updated_at=now()where id=1;insert into stats_equipe(operator_name,revenue,items,orders)values(clean_name,total_amount,item_count,1)on conflict(operator_name)do update set revenue=stats_equipe.revenue+excluded.revenue,items=stats_equipe.items+excluded.items,orders=stats_equipe.orders+1,updated_at=now();insert into sales_events(service_id,operator_name,revenue,items,orders,source,sale_id)values(current_service,clean_name,total_amount,item_count,1,'tab',basket_id);end;$$;

create or replace function public.enregistrer_commande_simple_detaillee(p_items jsonb,p_operator_name text)returns uuid language plpgsql security definer set search_path=public as $$
declare clean_name text:=public.nom_employe_connecte();current_service bigint;new_sale uuid:=gen_random_uuid();total_amount numeric;item_count integer;begin if jsonb_typeof(p_items)<>'array'or jsonb_array_length(p_items)<1 or jsonb_array_length(p_items)>100 then raise exception'Commande invalide';end if;select coalesce(sum((x->>'amount')::numeric),0),count(*)into total_amount,item_count from jsonb_array_elements(p_items)x;if total_amount<=0 then raise exception'Montant invalide';end if;perform fermer_service_si_inactif();select id into current_service from bar_services where status='open'limit 1;if current_service is null then begin insert into bar_services(name,opened_by)values(nom_service_automatique(),clean_name)returning id into current_service;exception when unique_violation then select id into current_service from bar_services where status='open'limit 1;end;end if;insert into stats_equipe(operator_name,revenue,items,orders)values(clean_name,total_amount,item_count,1)on conflict(operator_name)do update set revenue=stats_equipe.revenue+excluded.revenue,items=stats_equipe.items+excluded.items,orders=stats_equipe.orders+1,updated_at=now();insert into sales_events(service_id,operator_name,revenue,items,orders,source,sale_id)values(current_service,clean_name,total_amount,item_count,1,'order',new_sale);insert into team_audit_logs(sale_id,service_id,operator_name,source,action,item_name,quantity,unit_amount,total_amount)select new_sale,current_service,clean_name,'order','sale',left(item_label,80),qty,unit_amount,qty*unit_amount from(select coalesce(x->>'logName',x->>'name','Article')item_label,(x->>'amount')::numeric unit_amount,count(*)::integer qty from jsonb_array_elements(p_items)x group by 1,2)g;return new_sale;end;$$;

alter table public.team_audit_logs drop constraint if exists team_audit_logs_source_check;
alter table public.team_audit_logs add constraint team_audit_logs_source_check check(source in('tab','order','addition'));
create or replace function public.audit_ardoise_log()returns trigger language plpgsql security definer set search_path=public as $$
declare current_service bigint;begin if tg_op='INSERT'and new.operation in('payment','add')then select id into current_service from bar_services where status='open'limit 1;insert into team_audit_logs(sale_id,service_id,operator_name,source,action,item_name,quantity,unit_amount,total_amount,created_at)values(coalesce(new.sale_id,gen_random_uuid()),current_service,new.operator_name,case when new.operation='add'then'addition'else'tab'end,'sale',case when new.operation='add'then coalesce('Ardoise de '||nullif(trim(new.debtor_name),''),'Ajout à l’ardoise')else coalesce(new.item_name,'Montant libre')end,coalesce(new.quantity,1),new.amount/greatest(coalesce(new.quantity,1),1),new.amount,new.created_at);return new;elsif tg_op='DELETE'and old.operation='payment'then select service_id into current_service from team_audit_logs where sale_id=old.sale_id order by id limit 1;insert into team_audit_logs(sale_id,service_id,operator_name,source,action,item_name,quantity,unit_amount,total_amount)values(coalesce(old.sale_id,gen_random_uuid()),current_service,old.operator_name,'tab','cancel',coalesce(old.item_name,'Montant libre'),-coalesce(old.quantity,1),-(old.amount/greatest(coalesce(old.quantity,1),1)),-old.amount);return old;end if;if tg_op='DELETE'then return old;else return new;end if;end;$$;

insert into public.team_audit_logs(sale_id,service_id,operator_name,source,action,item_name,quantity,unit_amount,total_amount,created_at)
select coalesce(l.sale_id,gen_random_uuid()),s.id,l.operator_name,'addition','sale',coalesce('Ardoise de '||nullif(trim(l.debtor_name),''),'Ajout à l’ardoise'),1,l.amount,l.amount,l.created_at from ardoise_logs l left join lateral(select id from bar_services where opened_at<=l.created_at and coalesce(closed_at,now())>=l.created_at order by opened_at desc limit 1)s on true where l.operation='add'and not exists(select 1 from team_audit_logs a where a.source='addition'and lower(a.operator_name)=lower(l.operator_name)and a.created_at=l.created_at and a.total_amount=l.amount);

create or replace function public.remettre_ardoise_a_zero()returns void language plpgsql security definer set search_path=public as $$
declare admin_name text:=public.exiger_admin_mojito();begin insert into podium_manual_adjustments(week_start,normalized_name,name,adjustment,updated_by,updated_at)select date_trunc('week',(l.created_at at time zone'Europe/Paris')+interval'4 hours')-interval'4 hours',lower(trim(l.debtor_name)),(array_agg(trim(l.debtor_name)order by l.created_at desc))[1],sum(l.amount),admin_name,now()from ardoise_logs l where l.operation='add'and coalesce(l.counts_for_podium,true)and nullif(trim(l.debtor_name),'')is not null group by 1,2 on conflict(week_start,normalized_name)do update set adjustment=podium_manual_adjustments.adjustment+excluded.adjustment,name=excluded.name,updated_by=excluded.updated_by,updated_at=now();update ardoise_state set balance=0,peak=0,updated_at=now()where id=1;delete from ardoise_logs where id>0;end;$$;

revoke execute on function public.ajouter_ardoise_nominative(numeric,text,text)from anon,public;revoke execute on function public.ajouter_ardoise_nominative(numeric,text,text,boolean)from anon,public;revoke execute on function public.appliquer_operation(text,numeric,text,text)from anon,public;revoke execute on function public.appliquer_panier(jsonb,text)from anon,public;revoke execute on function public.enregistrer_commande_simple_detaillee(jsonb,text)from anon,public;revoke execute on function public.remettre_ardoise_a_zero()from anon,public;
grant execute on function public.ajouter_ardoise_nominative(numeric,text,text)to authenticated;grant execute on function public.ajouter_ardoise_nominative(numeric,text,text,boolean)to authenticated;grant execute on function public.appliquer_operation(text,numeric,text,text)to authenticated;grant execute on function public.appliquer_panier(jsonb,text)to authenticated;grant execute on function public.enregistrer_commande_simple_detaillee(jsonb,text)to authenticated;grant execute on function public.remettre_ardoise_a_zero()to authenticated;

-- Ferme l'accès anonyme aux fonctions administratives historiques.
revoke execute on function public.admin_ajuster_statistiques(text,text,text,numeric,integer,integer,text)from anon,public;revoke execute on function public.admin_annuler_correction(bigint,text)from anon,public;revoke execute on function public.admin_ajuster_statistiques_jour(text,text,text,numeric,integer,integer,text,timestamptz)from anon,public;revoke execute on function public.admin_remettre_stats_a_zero(text,text)from anon,public;revoke execute on function public.admin_supprimer_tous_cadeaux(text)from anon,public;revoke execute on function public.admin_supprimer_partie_archivee(bigint,text)from anon,public;revoke execute on function public.admin_supprimer_historique_jeux(text)from anon,public;revoke execute on function public.supprimer_cadeau(bigint,text)from anon,public;

-- Annulations : le propriétaire est le compte connecté, jamais le nom fourni.
create or replace function public.annuler_ligne_ardoise(p_log_id bigint,p_requester_name text)returns void language plpgsql security definer set search_path=public as $$
declare line ardoise_logs%rowtype;remaining integer;remove_order integer:=0;requester text:=public.nom_employe_connecte();begin select*into line from ardoise_logs where id=p_log_id for update;if not found or line.operation<>'payment'then raise exception'Ligne introuvable ou non annulable';end if;if lower(requester)<>lower(line.operator_name)and not public.est_admin_mojito()then raise exception'Tu ne peux pas annuler cette ligne';end if;delete from ardoise_logs where id=p_log_id;update ardoise_state set balance=balance+line.amount,peak=greatest(peak,balance+line.amount),updated_at=now()where id=1;if line.sale_id is not null then select count(*)into remaining from ardoise_logs where sale_id=line.sale_id;else select count(*)into remaining from ardoise_logs where operator_name=line.operator_name and created_at=line.created_at and operation='payment';end if;if remaining=0 then remove_order=1;end if;update stats_equipe set revenue=greatest(0,revenue-line.amount),items=greatest(0,items-coalesce(line.quantity,1)),orders=greatest(0,orders-remove_order),updated_at=now()where lower(operator_name)=lower(line.operator_name);delete from stats_equipe where revenue=0 and items=0 and orders=0;if line.sale_id is not null then update sales_events set revenue=greatest(0,revenue-line.amount),items=greatest(0,items-coalesce(line.quantity,1)),orders=greatest(0,orders-remove_order)where sale_id=line.sale_id;delete from sales_events where sale_id=line.sale_id and revenue=0 and items=0 and orders=0;end if;end;$$;

create or replace function public.annuler_commande_simple_detaillee(p_sale_id uuid,p_operator_name text)returns void language plpgsql security definer set search_path=public as $$
declare sale sales_events%rowtype;requester text:=public.nom_employe_connecte();begin select*into sale from sales_events where sale_id=p_sale_id and source='order'for update;if not found then raise exception'Commande introuvable';end if;if lower(requester)<>lower(sale.operator_name)and not public.est_admin_mojito()then raise exception'Action refusée';end if;insert into team_audit_logs(sale_id,service_id,operator_name,source,action,item_name,quantity,unit_amount,total_amount)select sale_id,service_id,operator_name,source,'cancel',item_name,-quantity,-unit_amount,-total_amount from team_audit_logs where sale_id=p_sale_id and action='sale';update stats_equipe set revenue=greatest(0,revenue-sale.revenue),items=greatest(0,items-sale.items),orders=greatest(0,orders-sale.orders),updated_at=now()where lower(operator_name)=lower(sale.operator_name);delete from stats_equipe where revenue=0 and items=0 and orders=0;delete from sales_events where id=sale.id;end;$$;

create or replace function public.remettre_stats_personnelles_a_zero(p_operator_name text)returns void language plpgsql security definer set search_path=public as $$begin delete from stats_equipe where lower(operator_name)=lower(public.nom_employe_connecte());end;$$;
revoke execute on function public.annuler_ligne_ardoise(bigint,text)from anon,public;revoke execute on function public.annuler_commande_simple_detaillee(uuid,text)from anon,public;revoke execute on function public.remettre_stats_personnelles_a_zero(text)from anon,public;
grant execute on function public.annuler_ligne_ardoise(bigint,text)to authenticated;grant execute on function public.annuler_commande_simple_detaillee(uuid,text)to authenticated;grant execute on function public.remettre_stats_personnelles_a_zero(text)to authenticated;

-- Enveloppes admin : les anciennes implémentations restent internes et reçoivent
-- le véritable nom de l'admin après vérification de auth.uid().
do $$begin
if to_regprocedure('public.admin_ajuster_statistiques_interne(text,text,text,numeric,integer,integer,text)')is null then alter function public.admin_ajuster_statistiques(text,text,text,numeric,integer,integer,text)rename to admin_ajuster_statistiques_interne;end if;
if to_regprocedure('public.admin_annuler_correction_interne(bigint,text)')is null then alter function public.admin_annuler_correction(bigint,text)rename to admin_annuler_correction_interne;end if;
if to_regprocedure('public.admin_ajuster_statistiques_jour_interne(text,text,text,numeric,integer,integer,text,timestamptz)')is null then alter function public.admin_ajuster_statistiques_jour(text,text,text,numeric,integer,integer,text,timestamptz)rename to admin_ajuster_statistiques_jour_interne;end if;
if to_regprocedure('public.admin_remettre_stats_a_zero_interne(text,text)')is null then alter function public.admin_remettre_stats_a_zero(text,text)rename to admin_remettre_stats_a_zero_interne;end if;
if to_regprocedure('public.admin_supprimer_tous_cadeaux_interne(text)')is null then alter function public.admin_supprimer_tous_cadeaux(text)rename to admin_supprimer_tous_cadeaux_interne;end if;
if to_regprocedure('public.admin_supprimer_partie_archivee_interne(bigint,text)')is null then alter function public.admin_supprimer_partie_archivee(bigint,text)rename to admin_supprimer_partie_archivee_interne;end if;
if to_regprocedure('public.admin_supprimer_historique_jeux_interne(text)')is null then alter function public.admin_supprimer_historique_jeux(text)rename to admin_supprimer_historique_jeux_interne;end if;
if to_regprocedure('public.supprimer_cadeau_interne(bigint,text)')is null then alter function public.supprimer_cadeau(bigint,text)rename to supprimer_cadeau_interne;end if;
end;$$;

create or replace function public.admin_ajuster_statistiques(p_requester_name text,p_target_name text,p_operation text,p_revenue numeric,p_items integer,p_orders integer,p_note text)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform admin_ajuster_statistiques_interne(a,p_target_name,p_operation,p_revenue,p_items,p_orders,p_note);end;$$;
create or replace function public.admin_annuler_correction(p_event_id bigint,p_requester_name text)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform admin_annuler_correction_interne(p_event_id,a);end;$$;
create or replace function public.admin_ajuster_statistiques_jour(p_requester_name text,p_target_name text,p_operation text,p_revenue numeric,p_items integer,p_orders integer,p_note text,p_effective_at timestamptz)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform admin_ajuster_statistiques_jour_interne(a,p_target_name,p_operation,p_revenue,p_items,p_orders,p_note,p_effective_at);end;$$;
create or replace function public.admin_remettre_stats_a_zero(p_requester_name text,p_target_name text)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform admin_remettre_stats_a_zero_interne(a,p_target_name);end;$$;
create or replace function public.admin_supprimer_tous_cadeaux(p_requester_name text)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform admin_supprimer_tous_cadeaux_interne(a);end;$$;
create or replace function public.admin_supprimer_partie_archivee(p_winner_id bigint,p_requester_name text)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform admin_supprimer_partie_archivee_interne(p_winner_id,a);end;$$;
create or replace function public.admin_supprimer_historique_jeux(p_requester_name text)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform admin_supprimer_historique_jeux_interne(a);end;$$;
create or replace function public.supprimer_cadeau(p_gift_id bigint,p_requester_name text)returns void language plpgsql security definer set search_path=public as $$declare a text:=public.exiger_admin_mojito();begin perform supprimer_cadeau_interne(p_gift_id,a);end;$$;

revoke all on function public.admin_ajuster_statistiques_interne(text,text,text,numeric,integer,integer,text)from public,anon,authenticated;revoke all on function public.admin_annuler_correction_interne(bigint,text)from public,anon,authenticated;revoke all on function public.admin_ajuster_statistiques_jour_interne(text,text,text,numeric,integer,integer,text,timestamptz)from public,anon,authenticated;revoke all on function public.admin_remettre_stats_a_zero_interne(text,text)from public,anon,authenticated;revoke all on function public.admin_supprimer_tous_cadeaux_interne(text)from public,anon,authenticated;revoke all on function public.admin_supprimer_partie_archivee_interne(bigint,text)from public,anon,authenticated;revoke all on function public.admin_supprimer_historique_jeux_interne(text)from public,anon,authenticated;revoke all on function public.supprimer_cadeau_interne(bigint,text)from public,anon,authenticated;
grant execute on function public.admin_ajuster_statistiques(text,text,text,numeric,integer,integer,text)to authenticated;grant execute on function public.admin_annuler_correction(bigint,text)to authenticated;grant execute on function public.admin_ajuster_statistiques_jour(text,text,text,numeric,integer,integer,text,timestamptz)to authenticated;grant execute on function public.admin_remettre_stats_a_zero(text,text)to authenticated;grant execute on function public.admin_supprimer_tous_cadeaux(text)to authenticated;grant execute on function public.admin_supprimer_partie_archivee(bigint,text)to authenticated;grant execute on function public.admin_supprimer_historique_jeux(text)to authenticated;grant execute on function public.supprimer_cadeau(bigint,text)to authenticated;

notify pgrst,'reload schema';

